In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
print("--- Dataset Summary ---")
for dirname, _, filenames in os.walk('/kaggle/input'):
    if len(filenames) > 0:
        print(f"Folder: {dirname} | Contains {len(filenames)} files")
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

--- Dataset Summary ---
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/test_set/test_set | Contains 4000 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/SeaLake | Contains 2600 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/Highway | Contains 2100 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/River | Contains 2100 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/Pasture | Contains 1600 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/Industrial | Contains 2100 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/Residential | Contains 2600 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/PermanentCrop | Contains 2100 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/AnnualCrop | Contains 2600 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/Forest | Contains 2600 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/HerbaceousVegetation | Contains 2600 files
Folder: /kaggle/input/models/sakshamgarg2323/eurosat/pytorch/default/1 | Contains 1 files

In [ ]:
import torch

if torch.cuda.is_available():
    print(f"GPU Connected: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not detected. Please check Accelerator settings.")

GPU Connected: Tesla T4

In [ ]:
import os
import sys
import torch
from torch import nn
from torch.utils.data import DataLoader, Subset
from torchvision.transforms import v2
from PIL import Image
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

In [ ]:
# setting up the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# defining the class mappings, could have been done simply by using image folders but forgot to do that
Class_Mapping = {
    'AnnualCrop': 0, 'Forest': 1, 'HerbaceousVegetation': 2,
    'Highway': 3, 'Industrial': 4, 'Pasture': 5,
    'PermanentCrop': 6, 'Residential': 7, 'River': 8, 'SeaLake': 9
}
# 1. Update the base path variable
base_path = '/kaggle/input/datasets/sakshamgarg2323/eurosat'

train_dir = os.path.join(base_path, 'train', 'train')
test_dir = os.path.join(base_path, 'test_set', 'test_set')

Using device: cuda

In [ ]:
class EuroSATLabeled(torch.utils.data.Dataset):
    def __init__(self, img_dir, transforms=None):
        self.img_dir = img_dir
        self.transforms = transforms
        self.data = []
        for class_name in os.listdir(self.img_dir):
            class_path = os.path.join(self.img_dir, class_name)
            if os.path.isdir(class_path):
                class_label = Class_Mapping[class_name]
                for img_name in os.listdir(class_path):
                      self.data.append((os.path.join(class_path, img_name), class_label, img_name))

    def __len__(self): return len(self.data)

    def __getitem__(self, idx):
        img_path, class_label, img_filename = self.data[idx]
        img = Image.open(img_path).convert('RGB')
        if self.transforms:
            img = self.transforms(img)
        return img, class_label, img_filename

class EuroSATUnlabeled(torch.utils.data.Dataset):
    def __init__(self, img_dir, transforms=None):
        self.img_dir = img_dir
        self.transforms = transforms
        self.data = []
        for img_name in os.listdir(self.img_dir):
              self.data.append((os.path.join(self.img_dir, img_name), img_name))

    def __len__(self): return len(self.data)

    def __getitem__(self, idx):
        img_path, img_filename = self.data[idx]
        img = Image.open(img_path).convert('RGB')
        if self.transforms:
            img = self.transforms(img)
        return img, img_filename

In [ ]:
EUROSAT_MEAN = [0.3444, 0.3803, 0.4078]
EUROSAT_STD  = [0.2025, 0.1366, 0.1148]
train_transforms = v2.Compose([
    v2.Resize((224,224), antialias=True),              # slightly larger before crop
    v2.RandomHorizontalFlip(p=0.5),
    v2.RandomVerticalFlip(p=0.5),
    v2.RandomApply([v2.RandomRotation(degrees=(90, 90))], p=0.5),   # only 90° multiples
    v2.RandomApply([v2.RandomRotation(degrees=(180, 180))], p=0.25),
    v2.ToImage(),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=EUROSAT_MEAN, std=EUROSAT_STD),
])

test_transforms = v2.Compose([
    v2.Resize((224, 224), antialias=True),   # ← same fix here
    v2.ToImage(),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=EUROSAT_MEAN, std=EUROSAT_STD),
])
tta_transform = v2.Compose([
    v2.Resize((224, 224), antialias=True),
    v2.RandomHorizontalFlip(p=0.5),
    v2.RandomVerticalFlip(p=0.5),
    # Restrict to 90/180/270 rotations to prevent black zero-padding
    v2.RandomApply([v2.RandomRotation(degrees=(90, 90))], p=0.5),
    v2.RandomApply([v2.RandomRotation(degrees=(180, 180))], p=0.25),
    v2.RandomApply([v2.RandomRotation(degrees=(270, 270))], p=0.25),
    v2.ToImage(),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=EUROSAT_MEAN, std=EUROSAT_STD),
])

# 3. Now initialize your datasets
full_train_aug = EuroSATLabeled(img_dir=train_dir, transforms=train_transforms)
full_train_no_aug = EuroSATLabeled(img_dir=train_dir, transforms=test_transforms)
test_dataset = EuroSATUnlabeled(img_dir=test_dir, transforms=test_transforms)
#class for preprocessing of labelled data from train.zip

targets = [item[1] for item in full_train_aug.data]
indices = list(range(len(full_train_aug)))

train_indices, val_indices = train_test_split(
    indices, test_size=0.2, stratify=targets, random_state=42
)

train_dataset = Subset(full_train_aug, train_indices)
val_dataset = Subset(full_train_no_aug, val_indices)
test_dataset = EuroSATUnlabeled(
    img_dir=test_dir,
    transforms=test_transforms
)
# Validation TTA loader (uses same val_indices split)
tta_val_base    = EuroSATLabeled(img_dir=train_dir, transforms=tta_transform)
tta_val_dataset = Subset(tta_val_base, val_indices)
tta_val_loader  = DataLoader(tta_val_dataset, batch_size=256, shuffle=False,
                             num_workers=4, pin_memory=True, persistent_workers=True)
batch_size = 256
# Test TTA loader (for submission)
tta_test_dataset = EuroSATUnlabeled(img_dir=test_dir, transforms=tta_transform)
tta_test_loader  = DataLoader(tta_test_dataset, batch_size=256, shuffle=False,
                              num_workers=4, pin_memory=True, persistent_workers=True)

In [ ]:
batch_size = 256

# --- [UPDATED] Hardware Acceleration for DataLoaders ---
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True,persistent_workers=True)
val_dataloader = DataLoader(
    val_dataset, batch_size=batch_size, shuffle=False,
    num_workers=4, pin_memory=True, persistent_workers=True   # ← was missing
)
test_dataloader = DataLoader(
    test_dataset, batch_size=batch_size, shuffle=False,
    num_workers=4, pin_memory=True, persistent_workers=True
)

print(f"Training samples: {len(train_dataset)}")
print(f"Validation samples: {len(val_dataset)}")
print(f"Submission samples: {len(test_dataset)}")

Training samples: 18400
Validation samples: 4600
Submission samples: 4000

In [ ]:
# import torch.nn.functional as F

# class BasicBlock(nn.Module):
#     expansion = 1
#     def __init__(self, in_channels, out_channels, stride=1):
#         super(BasicBlock, self).__init__()
#         self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
#         self.bn1 = nn.BatchNorm2d(out_channels)
#         self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False)
#         self.bn2 = nn.BatchNorm2d(out_channels)
#         self.shortcut = nn.Sequential()
#         if stride != 1 or in_channels != self.expansion * out_channels:
#             self.shortcut = nn.Sequential(
#                 nn.Conv2d(in_channels, self.expansion * out_channels, kernel_size=1, stride=stride, bias=False),
#                 nn.BatchNorm2d(self.expansion * out_channels)
#             )

#     def forward(self, x):
#         out = F.relu(self.bn1(self.conv1(x)))
#         out = self.bn2(self.conv2(out))
#         out += self.shortcut(x)
#         out = F.relu(out)
#         return out
# class Bottleneck(nn.Module):
#     expansion = 4 # This is crucial: Bottleneck increases out_channels by 4x

#     def __init__(self, in_channels, out_channels, stride=1):
#         super(Bottleneck, self).__init__()
#         # 1x1 conv to compress channels
#         self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=1, bias=False)
#         self.bn1 = nn.BatchNorm2d(out_channels)

#         # 3x3 conv
#         self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
#         self.bn2 = nn.BatchNorm2d(out_channels)

#         # 1x1 conv to expand channels back out
#         self.conv3 = nn.Conv2d(out_channels, self.expansion * out_channels, kernel_size=1, bias=False)
#         self.bn3 = nn.BatchNorm2d(self.expansion * out_channels)

#         self.shortcut = nn.Sequential()
#         if stride != 1 or in_channels != self.expansion * out_channels:
#             self.shortcut = nn.Sequential(
#                 nn.Conv2d(in_channels, self.expansion * out_channels, kernel_size=1, stride=stride, bias=False),
#                 nn.BatchNorm2d(self.expansion * out_channels)
#             )

#     def forward(self, x):
#         out = F.relu(self.bn1(self.conv1(x)))
#         out = F.relu(self.bn2(self.conv2(out)))
#         out = self.bn3(self.conv3(out))
#         out += self.shortcut(x)
#         out = F.relu(out)
#         return out

# class ResNet(nn.Module):
#     def __init__(self, block, num_blocks, num_classes=10):
#         super(ResNet, self).__init__()
#         self.in_channels = 64
#         self.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
#         self.bn1 = nn.BatchNorm2d(64)

#         self.layer1 = self._make_layer(block, 64, num_blocks[0], stride=1)
#         self.layer2 = self._make_layer(block, 128, num_blocks[1], stride=2)
#         self.layer3 = self._make_layer(block, 256, num_blocks[2], stride=2)
#         self.layer4 = self._make_layer(block, 512, num_blocks[3], stride=2)

#         self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
#         self.linear = nn.Linear(512 * block.expansion, num_classes)

#     def _make_layer(self, block, out_channels, num_blocks, stride):
#         strides = [stride] + [1] * (num_blocks - 1)
#         layers = []
#         for s in strides:
#             layers.append(block(self.in_channels, out_channels, s))
#             self.in_channels = out_channels * block.expansion
#         return nn.Sequential(*layers)

#     def forward(self, x):
#         out = F.relu(self.bn1(self.conv1(x)))
#         out = self.layer1(out)
#         out = self.layer2(out)
#         out = self.layer3(out)
#         out = self.layer4(out)
#         out = self.avgpool(out)
#         out = torch.flatten(out, 1)
#         out = self.linear(out)
#         return out

# def build_resnet50_64x64(num_classes):
#     # Change 'BasicBlock' to 'Bottleneck'
#     return ResNet(Bottleneck, [3, 4, 6, 3], num_classes=num_classes)

# model = build_resnet50_64x64(num_classes=len(Class_Mapping)).to(device)

# def init_weights(m):
#     if isinstance(m, nn.Conv2d):
#         nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
#     elif isinstance(m, nn.BatchNorm2d):
#         nn.init.constant_(m.weight, 1)
#         nn.init.constant_(m.bias, 0)


# model.apply(init_weights)
# print("Applied Kaiming Normal initialization.")

In [ ]:
import torchvision.models as models

# 1. Load the pretrained ResNet-18
# Using the updated weights API instead of the deprecated pretrained=True
model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)

# 2. Freeze all baseline convolutional layers
for param in model.parameters():
    param.requires_grad = False

# 3. Replace the final linear classification layer
# The 'fc' attribute in PyTorch ResNets is the final fully connected layer.
# By assigning a new nn.Linear module, it automatically has requires_grad=True.
num_ftrs = model.fc.in_features
print(num_ftrs)
model.fc = nn.Sequential(
    nn.Linear(num_ftrs, 1024),
    nn.BatchNorm1d(1024),
    nn.LeakyReLU(inplace=True),
    nn.Dropout(p=0.4),
    nn.Linear(1024,256),
    nn.BatchNorm1d(256),
    nn.ReLU(inplace=True),
    nn.Linear(256, len(Class_Mapping))
)


# Send the model to your configured device (GPU)
model = model.to(device)

print(f"Total parameters: {sum(p.numel() for p in model.parameters())}")
print(f"Trainable parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad)}")

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth

100%|██████████| 44.7M/44.7M [00:00<00:00, 181MB/s]

512
Total parameters: 11969354
Trainable parameters: 792842

In [ ]:

learning_rate = 0.01                  # Step 6: was 0.001 — fresh linear layer needs a higher LR
early_stop_patience = 80              # Step 8: new

loss_fn = nn.CrossEntropyLoss(label_smoothing=0.1)   # Step 7: was no smoothing

optimizer = torch.optim.AdamW(
    model.fc.parameters(),
    lr=learning_rate,
    weight_decay=1e-3,
    amsgrad=True
)

num_epochs = 80
warmup_epochs = 5

warmup_scheduler = torch.optim.lr_scheduler.LinearLR(
    optimizer, start_factor=0.1, end_factor=1.0, total_iters=warmup_epochs
)
cosine_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=num_epochs - warmup_epochs, eta_min=1e-6
)
scheduler = torch.optim.lr_scheduler.SequentialLR(
    optimizer,
    schedulers=[warmup_scheduler, cosine_scheduler],
    milestones=[warmup_epochs]
)

checkpoint_path = '/kaggle/working/EuroSAT_Build1_FrozenResNet18.pth'  # Step 11: was "ResNet50"
# model = torch.compile(model)
# print("Model successfully compiled and optimized.")

In [ ]:
def run_tta(model, dataloader, device, n_aug=10, labeled=True):
    """
    Runs n_aug passes over the dataloader. Each pass applies a different
    random augmentation (since transforms are stochastic). Softmax probs
    are accumulated then averaged — only then is argmax taken.
    shuffle=False guarantees every pass is in the same sample order.
    """
    model.eval()
    n        = len(dataloader.dataset)
    acc_prob = torch.zeros(n, len(Class_Mapping))  # accumulated probabilities
    labels_out, names_out = [], []

    for pass_idx in range(n_aug):
        ptr = 0
        with torch.no_grad():
            if labeled:
                for X, y, _ in dataloader:
                    X = X.to(device)
                    with torch.amp.autocast('cuda'):
                        logits = model(X)
                    acc_prob[ptr:ptr + X.size(0)] += torch.softmax(logits, dim=1).cpu()
                    if pass_idx == 0:               # collect labels once
                        labels_out.extend(y.tolist())
                    ptr += X.size(0)
            else:
                for X, names in dataloader:
                    X = X.to(device)
                    with torch.amp.autocast('cuda'):
                        logits = model(X)
                    acc_prob[ptr:ptr + X.size(0)] += torch.softmax(logits, dim=1).cpu()
                    if pass_idx == 0:               # collect filenames once
                        names_out.extend(names)
                    ptr += X.size(0)

        print(f"  TTA pass {pass_idx + 1}/{n_aug} complete")

    avg_probs = acc_prob / n_aug                    # average BEFORE argmax — this is the key step
    preds     = avg_probs.argmax(dim=1).numpy()

    return (preds, labels_out) if labeled else (preds, names_out)

In [ ]:
scaler = torch.amp.GradScaler('cuda')
# cutmix = v2.CutMix(num_classes=len(Class_Mapping), alpha=1.0)
cutmix = None  # ← Fix 1: was a bare `cutmix` expression → NameError. Define it explicitly.

def train_loop(dataloader, model, loss_fn, optimizer, cutmix=None):
    model.train()
    for m in model.modules():
        if isinstance(m, nn.BatchNorm2d):
            m.eval()

    size = len(dataloader.dataset)
    num_batches = len(dataloader)   # ← needed for average loss
    correct = 0
    running_loss = 0.0              # ← Fix 2: accumulate loss across batches

    for batch, (X, y, _) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        if cutmix is not None:
            X, y = cutmix(X, y)

        optimizer.zero_grad()

        with torch.amp.autocast('cuda'):
            pred = model(X)
            loss = loss_fn(pred, y)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()  # ← accumulate after scaler.update()

        if batch % 10 == 0:
            print(f"loss: {loss.item():>7f}  [{batch * dataloader.batch_size + len(X):>5d}/{size:>5d}]")

        if cutmix is not None:
            correct += (pred.argmax(1) == y.argmax(1)).type(torch.float).sum().item()
        else:
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    train_accuracy = correct / size
    avg_train_loss = running_loss / num_batches  # ← average over all batches

    print(f"Training Accuracy: {100*train_accuracy:.1f}%  Avg Loss: {avg_train_loss:.6f}")
    return train_accuracy, avg_train_loss  # ← return both
def test_loop(dataloader, model, loss_fn):
    model.eval()
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y, _ in dataloader:
            X, y = X.to(device), y.to(device)
            with torch.amp.autocast('cuda'):
                pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    accuracy = correct / size
    print(f"Validation: Accuracy={100*accuracy:.1f}%, Avg Loss={test_loss:.6f}\n")
    return test_loss, accuracy   # ← was only returning test_loss

In [ ]:
history = []
best_vacc = 0.0            # ← was best_vloss = float('inf')
early_stop_counter = 0
start_epoch = 0

for t in range(start_epoch, num_epochs):
    print(f"Epoch {t+1}")
    train_acc, train_loss = train_loop(train_dataloader, model, loss_fn, optimizer, cutmix=cutmix)
    vloss, vacc = test_loop(val_dataloader, model, loss_fn)

    scheduler.step()

    history.append({
        'epoch':      t + 1,
        'train_loss': train_loss,
        'train_acc':  train_acc,
        'val_loss':   vloss,
        'val_acc':    vacc,
        'lr':         scheduler.get_last_lr()[0]
    })

    if vacc > best_vacc:   # ← was: vloss < best_vloss
        print(f"Val accuracy improved {100*best_vacc:.2f}% → {100*vacc:.2f}%. Saving checkpoint...")
        best_vacc = vacc   # ← was: best_vloss = vloss
        early_stop_counter = 0
        torch.save({
            'epoch':           t + 1,
            'model_state':     model.state_dict(),
            'optimizer_state': optimizer.state_dict(),
            'best_vacc':       best_vacc   # ← was: best_vloss
        }, checkpoint_path)
    else:
        early_stop_counter += 1
        print(f"No improvement. Early stop counter: {early_stop_counter}/{early_stop_patience}")
        if early_stop_counter >= early_stop_patience:
            print(f"Early stopping at epoch {t+1}. Best val accuracy: {100*best_vacc:.2f}%")
            break

print(f"\nTraining complete. Best val accuracy: {100*best_vacc:.2f}%")
pd.DataFrame(history)

Epoch 1
loss: 2.386451  [  256/18400]
loss: 0.792951  [ 2816/18400]
loss: 0.725031  [ 5376/18400]
loss: 0.661324  [ 7936/18400]
loss: 0.731970  [10496/18400]
loss: 0.629450  [13056/18400]
loss: 0.657999  [15616/18400]
loss: 0.664185  [18176/18400]
Training Accuracy: 90.0%  Avg Loss: 0.782704
Validation: Accuracy=95.0%, Avg Loss=0.649875

Val accuracy improved 0.00% → 95.00%. Saving checkpoint...
Epoch 2
loss: 0.658495  [  256/18400]
loss: 0.661564  [ 2816/18400]
loss: 0.687750  [ 5376/18400]
loss: 0.663626  [ 7936/18400]
loss: 0.681087  [10496/18400]
loss: 0.691272  [13056/18400]
loss: 0.662748  [15616/18400]
loss: 0.659017  [18176/18400]
Training Accuracy: 94.5%  Avg Loss: 0.664846
Validation: Accuracy=94.8%, Avg Loss=0.651774

No improvement. Early stop counter: 1/80
Epoch 3
loss: 0.640730  [  256/18400]
loss: 0.663177  [ 2816/18400]
loss: 0.637192  [ 5376/18400]
loss: 0.616811  [ 7936/18400]
loss: 0.672214  [10496/18400]
loss: 0.684520  [13056/18400]
loss: 0.621227  [15616/18400]
loss: 0.680449  [18176/18400]
Training Accuracy: 94.8%  Avg Loss: 0.651889
Validation: Accuracy=95.2%, Avg Loss=0.643365

Val accuracy improved 95.00% → 95.24%. Saving checkpoint...
Epoch 4
loss: 0.616694  [  256/18400]
loss: 0.627925  [ 2816/18400]
loss: 0.625158  [ 5376/18400]
loss: 0.621776  [ 7936/18400]
loss: 0.621931  [10496/18400]
loss: 0.636614  [13056/18400]
loss: 0.639108  [15616/18400]
loss: 0.629336  [18176/18400]
Training Accuracy: 95.2%  Avg Loss: 0.637571
Validation: Accuracy=94.4%, Avg Loss=0.657661

No improvement. Early stop counter: 1/80
Epoch 5
loss: 0.598153  [  256/18400]
loss: 0.635237  [ 2816/18400]
loss: 0.603925  [ 5376/18400]
loss: 0.622730  [ 7936/18400]
loss: 0.625707  [10496/18400]
loss: 0.635924  [13056/18400]
loss: 0.621270  [15616/18400]
loss: 0.617191  [18176/18400]
Training Accuracy: 95.3%  Avg Loss: 0.634530
Validation: Accuracy=94.7%, Avg Loss=0.649116

No improvement. Early stop counter: 2/80
Epoch 6
loss: 0.599277  [  256/18400]
loss: 0.586821  [ 2816/18400]
loss: 0.604796  [ 5376/18400]
loss: 0.589887  [ 7936/18400]
loss: 0.612553  [10496/18400]
loss: 0.608793  [13056/18400]
loss: 0.632754  [15616/18400]
loss: 0.598034  [18176/18400]
Training Accuracy: 95.8%  Avg Loss: 0.621127
Validation: Accuracy=95.4%, Avg Loss=0.633192

Val accuracy improved 95.24% → 95.41%. Saving checkpoint...
Epoch 7
loss: 0.622911  [  256/18400]
loss: 0.610922  [ 2816/18400]
loss: 0.632579  [ 5376/18400]
loss: 0.601899  [ 7936/18400]
loss: 0.599709  [10496/18400]
loss: 0.641520  [13056/18400]
loss: 0.623200  [15616/18400]
loss: 0.606872  [18176/18400]
Training Accuracy: 96.0%  Avg Loss: 0.615708
Validation: Accuracy=95.5%, Avg Loss=0.625461

Val accuracy improved 95.41% → 95.50%. Saving checkpoint...
Epoch 8
loss: 0.593214  [  256/18400]
loss: 0.579717  [ 2816/18400]
loss: 0.602863  [ 5376/18400]
loss: 0.612058  [ 7936/18400]
loss: 0.606385  [10496/18400]
loss: 0.595492  [13056/18400]
loss: 0.601590  [15616/18400]
loss: 0.593377  [18176/18400]
Training Accuracy: 96.6%  Avg Loss: 0.601916
Validation: Accuracy=96.1%, Avg Loss=0.607313

Val accuracy improved 95.50% → 96.09%. Saving checkpoint...
Epoch 9
loss: 0.587606  [  256/18400]
loss: 0.598944  [ 2816/18400]
loss: 0.579065  [ 5376/18400]
loss: 0.603072  [ 7936/18400]
loss: 0.611262  [10496/18400]
loss: 0.634180  [13056/18400]
loss: 0.576278  [15616/18400]
loss: 0.647696  [18176/18400]
Training Accuracy: 96.8%  Avg Loss: 0.599074
Validation: Accuracy=95.9%, Avg Loss=0.608209

No improvement. Early stop counter: 1/80
Epoch 10
loss: 0.581543  [  256/18400]
loss: 0.622654  [ 2816/18400]
loss: 0.563743  [ 5376/18400]
loss: 0.592816  [ 7936/18400]
loss: 0.575160  [10496/18400]
loss: 0.598364  [13056/18400]
loss: 0.582655  [15616/18400]
loss: 0.590598  [18176/18400]
Training Accuracy: 97.0%  Avg Loss: 0.590164
Validation: Accuracy=96.0%, Avg Loss=0.604926

No improvement. Early stop counter: 2/80
Epoch 11
loss: 0.575529  [  256/18400]
loss: 0.599243  [ 2816/18400]
loss: 0.571913  [ 5376/18400]
loss: 0.563123  [ 7936/18400]
loss: 0.578861  [10496/18400]
loss: 0.578684  [13056/18400]
loss: 0.602154  [15616/18400]
loss: 0.597856  [18176/18400]
Training Accuracy: 97.0%  Avg Loss: 0.589808
Validation: Accuracy=96.1%, Avg Loss=0.599989

No improvement. Early stop counter: 3/80
Epoch 12
loss: 0.564439  [  256/18400]
loss: 0.552472  [ 2816/18400]
loss: 0.568859  [ 5376/18400]
loss: 0.588071  [ 7936/18400]
loss: 0.543874  [10496/18400]
loss: 0.571089  [13056/18400]
loss: 0.549989  [15616/18400]
loss: 0.560125  [18176/18400]
Training Accuracy: 97.3%  Avg Loss: 0.581261
Validation: Accuracy=95.9%, Avg Loss=0.604085

No improvement. Early stop counter: 4/80
Epoch 13
loss: 0.584294  [  256/18400]
loss: 0.555833  [ 2816/18400]
loss: 0.573997  [ 5376/18400]
loss: 0.593844  [ 7936/18400]
loss: 0.622676  [10496/18400]
loss: 0.602773  [13056/18400]
loss: 0.589359  [15616/18400]
loss: 0.588775  [18176/18400]
Training Accuracy: 97.3%  Avg Loss: 0.580112
Validation: Accuracy=96.0%, Avg Loss=0.608968

No improvement. Early stop counter: 5/80
Epoch 14
loss: 0.570734  [  256/18400]
loss: 0.578260  [ 2816/18400]
loss: 0.557229  [ 5376/18400]
loss: 0.622278  [ 7936/18400]
loss: 0.574501  [10496/18400]
loss: 0.561680  [13056/18400]
loss: 0.574764  [15616/18400]
loss: 0.570813  [18176/18400]
Training Accuracy: 97.6%  Avg Loss: 0.578285
Validation: Accuracy=96.5%, Avg Loss=0.596083

Val accuracy improved 96.09% → 96.50%. Saving checkpoint...
Epoch 15
loss: 0.568653  [  256/18400]
loss: 0.558953  [ 2816/18400]
loss: 0.583296  [ 5376/18400]
loss: 0.561237  [ 7936/18400]
loss: 0.549064  [10496/18400]
loss: 0.556692  [13056/18400]
loss: 0.580099  [15616/18400]
loss: 0.585390  [18176/18400]
Training Accuracy: 97.7%  Avg Loss: 0.572786
Validation: Accuracy=96.2%, Avg Loss=0.601535

No improvement. Early stop counter: 1/80
Epoch 16
loss: 0.585798  [  256/18400]
loss: 0.581564  [ 2816/18400]
loss: 0.581151  [ 5376/18400]
loss: 0.588628  [ 7936/18400]
loss: 0.588867  [10496/18400]
loss: 0.569370  [13056/18400]
loss: 0.589198  [15616/18400]
loss: 0.565146  [18176/18400]
Training Accuracy: 97.8%  Avg Loss: 0.572059
Validation: Accuracy=96.2%, Avg Loss=0.595947

No improvement. Early stop counter: 2/80
Epoch 17
loss: 0.562371  [  256/18400]
loss: 0.574435  [ 2816/18400]
loss: 0.555155  [ 5376/18400]
loss: 0.585241  [ 7936/18400]
loss: 0.557075  [10496/18400]
loss: 0.558842  [13056/18400]
loss: 0.560206  [15616/18400]
loss: 0.557569  [18176/18400]
Training Accuracy: 97.9%  Avg Loss: 0.566401
Validation: Accuracy=96.4%, Avg Loss=0.592122

No improvement. Early stop counter: 3/80
Epoch 18
loss: 0.567306  [  256/18400]
loss: 0.568915  [ 2816/18400]
loss: 0.562618  [ 5376/18400]
loss: 0.556794  [ 7936/18400]
loss: 0.579383  [10496/18400]
loss: 0.565187  [13056/18400]
loss: 0.547486  [15616/18400]
loss: 0.568044  [18176/18400]
Training Accuracy: 97.9%  Avg Loss: 0.566930
Validation: Accuracy=96.5%, Avg Loss=0.593831

No improvement. Early stop counter: 4/80
Epoch 19
loss: 0.562714  [  256/18400]
loss: 0.546764  [ 2816/18400]
loss: 0.554627  [ 5376/18400]
loss: 0.577013  [ 7936/18400]
loss: 0.563307  [10496/18400]
loss: 0.557155  [13056/18400]
loss: 0.558079  [15616/18400]
loss: 0.567465  [18176/18400]
Training Accuracy: 98.1%  Avg Loss: 0.562702
Validation: Accuracy=96.2%, Avg Loss=0.599067

No improvement. Early stop counter: 5/80
Epoch 20
loss: 0.564983  [  256/18400]
loss: 0.540048  [ 2816/18400]
loss: 0.537674  [ 5376/18400]
loss: 0.551160  [ 7936/18400]
loss: 0.567326  [10496/18400]
loss: 0.573617  [13056/18400]
loss: 0.552788  [15616/18400]
loss: 0.554063  [18176/18400]
Training Accuracy: 98.4%  Avg Loss: 0.558347
Validation: Accuracy=96.4%, Avg Loss=0.590630

No improvement. Early stop counter: 6/80
Epoch 21
loss: 0.540425  [  256/18400]
loss: 0.543634  [ 2816/18400]
loss: 0.560928  [ 5376/18400]
loss: 0.561823  [ 7936/18400]
loss: 0.566637  [10496/18400]
loss: 0.580006  [13056/18400]
loss: 0.561136  [15616/18400]
loss: 0.555554  [18176/18400]
Training Accuracy: 98.3%  Avg Loss: 0.560564
Validation: Accuracy=96.3%, Avg Loss=0.597304

No improvement. Early stop counter: 7/80
Epoch 22
loss: 0.554164  [  256/18400]
loss: 0.555426  [ 2816/18400]
loss: 0.540241  [ 5376/18400]
loss: 0.558178  [ 7936/18400]
loss: 0.552128  [10496/18400]
loss: 0.544228  [13056/18400]
loss: 0.557008  [15616/18400]
loss: 0.552660  [18176/18400]
Training Accuracy: 98.4%  Avg Loss: 0.555835
Validation: Accuracy=96.7%, Avg Loss=0.587918

Val accuracy improved 96.50% → 96.74%. Saving checkpoint...
Epoch 23
loss: 0.551143  [  256/18400]
loss: 0.552098  [ 2816/18400]
loss: 0.543221  [ 5376/18400]
loss: 0.575867  [ 7936/18400]
loss: 0.560149  [10496/18400]
loss: 0.552841  [13056/18400]
loss: 0.563828  [15616/18400]
loss: 0.571603  [18176/18400]
Training Accuracy: 98.3%  Avg Loss: 0.557790
Validation: Accuracy=96.6%, Avg Loss=0.590441

No improvement. Early stop counter: 1/80
Epoch 24
loss: 0.540999  [  256/18400]
loss: 0.527994  [ 2816/18400]
loss: 0.554434  [ 5376/18400]
loss: 0.546149  [ 7936/18400]
loss: 0.553742  [10496/18400]
loss: 0.544218  [13056/18400]
loss: 0.546742  [15616/18400]
loss: 0.562503  [18176/18400]
Training Accuracy: 98.4%  Avg Loss: 0.553147
Validation: Accuracy=96.7%, Avg Loss=0.585965

No improvement. Early stop counter: 2/80
Epoch 25
loss: 0.525089  [  256/18400]
loss: 0.538099  [ 2816/18400]
loss: 0.534297  [ 5376/18400]
loss: 0.553996  [ 7936/18400]
loss: 0.558610  [10496/18400]
loss: 0.549050  [13056/18400]
loss: 0.541554  [15616/18400]
loss: 0.545052  [18176/18400]
Training Accuracy: 98.7%  Avg Loss: 0.548117
Validation: Accuracy=96.4%, Avg Loss=0.588596

No improvement. Early stop counter: 3/80
Epoch 26
loss: 0.538760  [  256/18400]
loss: 0.550362  [ 2816/18400]
loss: 0.553771  [ 5376/18400]
loss: 0.551840  [ 7936/18400]
loss: 0.554691  [10496/18400]
loss: 0.531870  [13056/18400]
loss: 0.553744  [15616/18400]
loss: 0.540663  [18176/18400]
Training Accuracy: 98.6%  Avg Loss: 0.548216
Validation: Accuracy=96.8%, Avg Loss=0.584825

Val accuracy improved 96.74% → 96.78%. Saving checkpoint...
Epoch 27
loss: 0.535807  [  256/18400]
loss: 0.549088  [ 2816/18400]
loss: 0.543924  [ 5376/18400]
loss: 0.541814  [ 7936/18400]
loss: 0.548720  [10496/18400]
loss: 0.571614  [13056/18400]
loss: 0.544574  [15616/18400]
loss: 0.540152  [18176/18400]
Training Accuracy: 98.7%  Avg Loss: 0.549970
Validation: Accuracy=96.9%, Avg Loss=0.584093

Val accuracy improved 96.78% → 96.89%. Saving checkpoint...
Epoch 28
loss: 0.532601  [  256/18400]
loss: 0.540159  [ 2816/18400]
loss: 0.554411  [ 5376/18400]
loss: 0.571340  [ 7936/18400]
loss: 0.549774  [10496/18400]
loss: 0.546540  [13056/18400]
loss: 0.540337  [15616/18400]
loss: 0.550639  [18176/18400]
Training Accuracy: 98.8%  Avg Loss: 0.546121
Validation: Accuracy=96.6%, Avg Loss=0.583632

No improvement. Early stop counter: 1/80
Epoch 29
loss: 0.537679  [  256/18400]
loss: 0.564747  [ 2816/18400]
loss: 0.540144  [ 5376/18400]
loss: 0.568611  [ 7936/18400]
loss: 0.547891  [10496/18400]
loss: 0.537402  [13056/18400]
loss: 0.543715  [15616/18400]
loss: 0.534018  [18176/18400]
Training Accuracy: 98.8%  Avg Loss: 0.544142
Validation: Accuracy=97.0%, Avg Loss=0.580783

Val accuracy improved 96.89% → 97.04%. Saving checkpoint...
Epoch 30
loss: 0.542176  [  256/18400]
loss: 0.534650  [ 2816/18400]
loss: 0.540280  [ 5376/18400]
loss: 0.552063  [ 7936/18400]
loss: 0.528956  [10496/18400]
loss: 0.529051  [13056/18400]
loss: 0.539525  [15616/18400]
loss: 0.539346  [18176/18400]
Training Accuracy: 99.0%  Avg Loss: 0.542183
Validation: Accuracy=96.8%, Avg Loss=0.587104

No improvement. Early stop counter: 1/80
Epoch 31
loss: 0.547410  [  256/18400]
loss: 0.548566  [ 2816/18400]
loss: 0.526700  [ 5376/18400]
loss: 0.530824  [ 7936/18400]
loss: 0.545043  [10496/18400]
loss: 0.554243  [13056/18400]
loss: 0.558793  [15616/18400]
loss: 0.535307  [18176/18400]
Training Accuracy: 99.0%  Avg Loss: 0.541475
Validation: Accuracy=96.7%, Avg Loss=0.580756

No improvement. Early stop counter: 2/80
Epoch 32
loss: 0.534372  [  256/18400]
loss: 0.537513  [ 2816/18400]
loss: 0.548960  [ 5376/18400]
loss: 0.538500  [ 7936/18400]
loss: 0.531229  [10496/18400]
loss: 0.544418  [13056/18400]
loss: 0.543982  [15616/18400]
loss: 0.527431  [18176/18400]
Training Accuracy: 99.0%  Avg Loss: 0.538918
Validation: Accuracy=96.7%, Avg Loss=0.582221

No improvement. Early stop counter: 3/80
Epoch 33
loss: 0.549853  [  256/18400]
loss: 0.538624  [ 2816/18400]
loss: 0.538934  [ 5376/18400]
loss: 0.530721  [ 7936/18400]
loss: 0.545254  [10496/18400]
loss: 0.556457  [13056/18400]
loss: 0.546249  [15616/18400]
loss: 0.533356  [18176/18400]
Training Accuracy: 98.9%  Avg Loss: 0.538859
Validation: Accuracy=97.1%, Avg Loss=0.582574

Val accuracy improved 97.04% → 97.13%. Saving checkpoint...
Epoch 34
loss: 0.538570  [  256/18400]
loss: 0.536023  [ 2816/18400]
loss: 0.537631  [ 5376/18400]
loss: 0.543425  [ 7936/18400]
loss: 0.546826  [10496/18400]
loss: 0.537378  [13056/18400]
loss: 0.534318  [15616/18400]
loss: 0.528428  [18176/18400]
Training Accuracy: 99.2%  Avg Loss: 0.537352
Validation: Accuracy=96.6%, Avg Loss=0.584744

No improvement. Early stop counter: 1/80
Epoch 35
loss: 0.542782  [  256/18400]
loss: 0.531524  [ 2816/18400]
loss: 0.544595  [ 5376/18400]
loss: 0.545584  [ 7936/18400]
loss: 0.535390  [10496/18400]
loss: 0.547212  [13056/18400]
loss: 0.534454  [15616/18400]
loss: 0.533440  [18176/18400]
Training Accuracy: 99.2%  Avg Loss: 0.534768
Validation: Accuracy=96.8%, Avg Loss=0.581977

No improvement. Early stop counter: 2/80
Epoch 36
loss: 0.551888  [  256/18400]
loss: 0.534289  [ 2816/18400]
loss: 0.527821  [ 5376/18400]
loss: 0.538184  [ 7936/18400]
loss: 0.540606  [10496/18400]
loss: 0.535343  [13056/18400]
loss: 0.531311  [15616/18400]
loss: 0.521351  [18176/18400]
Training Accuracy: 99.2%  Avg Loss: 0.534291
Validation: Accuracy=96.8%, Avg Loss=0.582818

No improvement. Early stop counter: 3/80
Epoch 37
loss: 0.528320  [  256/18400]
loss: 0.526654  [ 2816/18400]
loss: 0.544248  [ 5376/18400]
loss: 0.527524  [ 7936/18400]
loss: 0.539107  [10496/18400]
loss: 0.549110  [13056/18400]
loss: 0.548276  [15616/18400]
loss: 0.522920  [18176/18400]
Training Accuracy: 99.3%  Avg Loss: 0.532755
Validation: Accuracy=96.8%, Avg Loss=0.581055

No improvement. Early stop counter: 4/80
Epoch 38
loss: 0.534123  [  256/18400]
loss: 0.522186  [ 2816/18400]
loss: 0.525932  [ 5376/18400]
loss: 0.553756  [ 7936/18400]
loss: 0.524127  [10496/18400]
loss: 0.533238  [13056/18400]
loss: 0.534112  [15616/18400]
loss: 0.533971  [18176/18400]
Training Accuracy: 99.3%  Avg Loss: 0.532720
Validation: Accuracy=96.9%, Avg Loss=0.580783

No improvement. Early stop counter: 5/80
Epoch 39
loss: 0.521226  [  256/18400]
loss: 0.527039  [ 2816/18400]
loss: 0.533178  [ 5376/18400]
loss: 0.529702  [ 7936/18400]
loss: 0.529280  [10496/18400]
loss: 0.526066  [13056/18400]
loss: 0.531351  [15616/18400]
loss: 0.532921  [18176/18400]
Training Accuracy: 99.3%  Avg Loss: 0.531146
Validation: Accuracy=96.8%, Avg Loss=0.580811

No improvement. Early stop counter: 6/80
Epoch 40
loss: 0.527413  [  256/18400]
loss: 0.528736  [ 2816/18400]
loss: 0.542731  [ 5376/18400]
loss: 0.525883  [ 7936/18400]
loss: 0.532894  [10496/18400]
loss: 0.540298  [13056/18400]
loss: 0.520995  [15616/18400]
loss: 0.537326  [18176/18400]
Training Accuracy: 99.4%  Avg Loss: 0.529526
Validation: Accuracy=96.8%, Avg Loss=0.579970

No improvement. Early stop counter: 7/80
Epoch 41
loss: 0.527251  [  256/18400]
loss: 0.522131  [ 2816/18400]
loss: 0.532470  [ 5376/18400]
loss: 0.528892  [ 7936/18400]
loss: 0.528871  [10496/18400]
loss: 0.521903  [13056/18400]
loss: 0.529486  [15616/18400]
loss: 0.535902  [18176/18400]
Training Accuracy: 99.5%  Avg Loss: 0.527901
Validation: Accuracy=97.1%, Avg Loss=0.578179

No improvement. Early stop counter: 8/80
Epoch 42
loss: 0.540047  [  256/18400]
loss: 0.527432  [ 2816/18400]
loss: 0.534928  [ 5376/18400]
loss: 0.523248  [ 7936/18400]
loss: 0.534450  [10496/18400]
loss: 0.521521  [13056/18400]
loss: 0.535615  [15616/18400]
loss: 0.524400  [18176/18400]
Training Accuracy: 99.5%  Avg Loss: 0.527351
Validation: Accuracy=96.7%, Avg Loss=0.580404

No improvement. Early stop counter: 9/80
Epoch 43
loss: 0.524717  [  256/18400]
loss: 0.535117  [ 2816/18400]
loss: 0.520081  [ 5376/18400]
loss: 0.530725  [ 7936/18400]
loss: 0.526695  [10496/18400]
loss: 0.525556  [13056/18400]
loss: 0.527917  [15616/18400]
loss: 0.526163  [18176/18400]
Training Accuracy: 99.5%  Avg Loss: 0.527324
Validation: Accuracy=96.8%, Avg Loss=0.579264

No improvement. Early stop counter: 10/80
Epoch 44
loss: 0.527595  [  256/18400]
loss: 0.529779  [ 2816/18400]
loss: 0.524519  [ 5376/18400]
loss: 0.521337  [ 7936/18400]
loss: 0.529026  [10496/18400]
loss: 0.528542  [13056/18400]
loss: 0.530476  [15616/18400]
loss: 0.524355  [18176/18400]
Training Accuracy: 99.6%  Avg Loss: 0.525518
Validation: Accuracy=96.9%, Avg Loss=0.577528

No improvement. Early stop counter: 11/80
Epoch 45
loss: 0.521472  [  256/18400]
loss: 0.530130  [ 2816/18400]
loss: 0.520661  [ 5376/18400]
loss: 0.520125  [ 7936/18400]
loss: 0.526287  [10496/18400]
loss: 0.520583  [13056/18400]
loss: 0.531105  [15616/18400]
loss: 0.528615  [18176/18400]
Training Accuracy: 99.5%  Avg Loss: 0.525347
Validation: Accuracy=96.9%, Avg Loss=0.579427

No improvement. Early stop counter: 12/80
Epoch 46
loss: 0.527952  [  256/18400]
loss: 0.523557  [ 2816/18400]
loss: 0.513012  [ 5376/18400]
loss: 0.526386  [ 7936/18400]
loss: 0.522382  [10496/18400]
loss: 0.530432  [13056/18400]
loss: 0.526015  [15616/18400]
loss: 0.520745  [18176/18400]
Training Accuracy: 99.6%  Avg Loss: 0.523393
Validation: Accuracy=96.9%, Avg Loss=0.577745

No improvement. Early stop counter: 13/80
Epoch 47
loss: 0.518108  [  256/18400]
loss: 0.522853  [ 2816/18400]
loss: 0.517969  [ 5376/18400]
loss: 0.517839  [ 7936/18400]
loss: 0.517850  [10496/18400]
loss: 0.515227  [13056/18400]
loss: 0.526986  [15616/18400]
loss: 0.531872  [18176/18400]
Training Accuracy: 99.6%  Avg Loss: 0.522424
Validation: Accuracy=96.9%, Avg Loss=0.576172

No improvement. Early stop counter: 14/80
Epoch 48
loss: 0.521062  [  256/18400]
loss: 0.518878  [ 2816/18400]
loss: 0.527468  [ 5376/18400]
loss: 0.539504  [ 7936/18400]
loss: 0.519872  [10496/18400]
loss: 0.513345  [13056/18400]
loss: 0.522366  [15616/18400]
loss: 0.515221  [18176/18400]
Training Accuracy: 99.7%  Avg Loss: 0.522047
Validation: Accuracy=96.8%, Avg Loss=0.578423

No improvement. Early stop counter: 15/80
Epoch 49
loss: 0.516704  [  256/18400]
loss: 0.522717  [ 2816/18400]
loss: 0.521091  [ 5376/18400]
loss: 0.514942  [ 7936/18400]
loss: 0.519383  [10496/18400]
loss: 0.528883  [13056/18400]
loss: 0.520377  [15616/18400]
loss: 0.518693  [18176/18400]
Training Accuracy: 99.6%  Avg Loss: 0.522413
Validation: Accuracy=96.8%, Avg Loss=0.576036

No improvement. Early stop counter: 16/80
Epoch 50
loss: 0.516761  [  256/18400]
loss: 0.512122  [ 2816/18400]
loss: 0.516920  [ 5376/18400]
loss: 0.525361  [ 7936/18400]
loss: 0.519284  [10496/18400]
loss: 0.516701  [13056/18400]
loss: 0.515535  [15616/18400]
loss: 0.522678  [18176/18400]
Training Accuracy: 99.7%  Avg Loss: 0.520100
Validation: Accuracy=96.9%, Avg Loss=0.576362

No improvement. Early stop counter: 17/80
Epoch 51
loss: 0.522814  [  256/18400]
loss: 0.518321  [ 2816/18400]
loss: 0.524047  [ 5376/18400]
loss: 0.533223  [ 7936/18400]
loss: 0.518331  [10496/18400]
loss: 0.535911  [13056/18400]
loss: 0.517270  [15616/18400]
loss: 0.516404  [18176/18400]
Training Accuracy: 99.7%  Avg Loss: 0.521703
Validation: Accuracy=97.0%, Avg Loss=0.575195

No improvement. Early stop counter: 18/80
Epoch 52
loss: 0.516249  [  256/18400]
loss: 0.521918  [ 2816/18400]
loss: 0.520133  [ 5376/18400]
loss: 0.521140  [ 7936/18400]
loss: 0.519456  [10496/18400]
loss: 0.529536  [13056/18400]
loss: 0.514112  [15616/18400]
loss: 0.515568  [18176/18400]
Training Accuracy: 99.8%  Avg Loss: 0.518933

    epoch  train_loss  train_acc  val_loss   val_acc        lr
0       1    0.782704   0.900380  0.649875  0.950000  0.002800
1       2    0.664846   0.944837  0.651774  0.947609  0.004600
2       3    0.651889   0.947663  0.643365  0.952391  0.006400
3       4    0.637571   0.952337  0.657661  0.943913  0.008200
4       5    0.634530   0.952989  0.649116  0.946522  0.010000
..    ...         ...        ...       ...       ...       ...
75     76    0.514647   0.998315  0.572591  0.970000  0.000071
76     77    0.514198   0.998913  0.572456  0.970870  0.000040
77     78    0.514383   0.998804  0.572591  0.971522  0.000019
78     79    0.514536   0.998587  0.572673  0.970870  0.000005
79     80    0.514976   0.998424  0.573079  0.970435  0.000001

[80 rows x 6 columns]

In [ ]:
# --- Load best checkpoint ---
print("Loading best checkpoint...")
model_path = "/kaggle/input/models/sakshamgarg2323/eurosat/pytorch/default/1/EuroSAT_Build1_FrozenResNet18.pth"

# 1. Load the checkpoint file
checkpoint = torch.load(model_path, map_location=device)

# 2. Extract the weights using the correct key (try 'model_state' or 'state_dict')
# If you get a KeyError here, change 'model_state' to 'state_dict'
model.load_state_dict(checkpoint['model_state'])
# --- Step 4: TTA Validation ---
print("\nRunning TTA on validation set...")
tta_preds, true_labels = run_tta(model, tta_val_loader, device, n_aug=15, labeled=True)

tta_acc = (tta_preds == np.array(true_labels)).mean()
print(f"\nTTA Validation Accuracy: {100 * tta_acc:.2f}%")
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, tta_preds))
print("\nClassification Report:")
print(classification_report(true_labels, tta_preds, target_names=list(Class_Mapping.keys())))

# --- Step 5: TTA Test Submission ---
print("\nRunning TTA on test set...")
tta_test_preds, filenames = run_tta(model, tta_test_loader, device, n_aug=15, labeled=False)

submission_df = pd.DataFrame({'image_id': filenames, 'label': tta_test_preds})
submission_df = submission_df.sort_values('image_id').reset_index(drop=True)
submission_df.to_csv('2025MT11352_CNN.csv', index=False)
print(f"Submission saved — {len(submission_df)} predictions.")

Loading best checkpoint...

Running TTA on validation set...
  TTA pass 1/15 complete
  TTA pass 2/15 complete
  TTA pass 3/15 complete
  TTA pass 4/15 complete
  TTA pass 5/15 complete
  TTA pass 6/15 complete
  TTA pass 7/15 complete
  TTA pass 8/15 complete
  TTA pass 9/15 complete
  TTA pass 10/15 complete
  TTA pass 11/15 complete
  TTA pass 12/15 complete
  TTA pass 13/15 complete
  TTA pass 14/15 complete
  TTA pass 15/15 complete

TTA Validation Accuracy: 97.85%

Confusion Matrix:
[[508   0   1   0   0   4   5   0   2   0]
 [  0 520   0   0   0   0   0   0   0   0]
 [  0   1 511   1   0   4   2   1   0   0]
 [  2   0   1 406   0   0   4   2   5   0]
 [  0   0   0   3 413   0   0   4   0   0]
 [  5   0   3   3   0 307   1   0   1   0]
 [  7   0   9   1   1   1 400   1   0   0]
 [  0   0   0   1   4   0   0 515   0   0]
 [  2   0   0  13   1   2   0   0 402   0]
 [  0   0   1   0   0   0   0   0   0 519]]

Classification Report:
                      precision    recall  f1-score   support

          AnnualCrop       0.97      0.98      0.97       520
              Forest       1.00      1.00      1.00       520
HerbaceousVegetation       0.97      0.98      0.98       520
             Highway       0.95      0.97      0.96       420
          Industrial       0.99      0.98      0.98       420
             Pasture       0.97      0.96      0.96       320
       PermanentCrop       0.97      0.95      0.96       420
         Residential       0.98      0.99      0.99       520
               River       0.98      0.96      0.97       420
             SeaLake       1.00      1.00      1.00       520

            accuracy                           0.98      4600
           macro avg       0.98      0.98      0.98      4600
        weighted avg       0.98      0.98      0.98      4600


Running TTA on test set...
  TTA pass 1/15 complete
  TTA pass 2/15 complete
  TTA pass 3/15 complete
  TTA pass 4/15 complete
  TTA pass 5/15 complete
  TTA pass 6/15 complete
  TTA pass 7/15 complete
  TTA pass 8/15 complete
  TTA pass 9/15 complete
  TTA pass 10/15 complete
  TTA pass 11/15 complete
  TTA pass 12/15 complete
  TTA pass 13/15 complete
  TTA pass 14/15 complete
  TTA pass 15/15 complete
Submission saved — 4000 predictions.

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
print("--- Dataset Summary ---")
for dirname, _, filenames in os.walk('/kaggle/input'):
    if len(filenames) > 0:
        print(f"Folder: {dirname} | Contains {len(filenames)} files")
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

--- Dataset Summary ---
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/test_set/test_set | Contains 4000 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/SeaLake | Contains 2600 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/Highway | Contains 2100 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/River | Contains 2100 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/Pasture | Contains 1600 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/Industrial | Contains 2100 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/Residential | Contains 2600 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/PermanentCrop | Contains 2100 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/AnnualCrop | Contains 2600 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/Forest | Contains 2600 files
Folder: /kaggle/input/datasets/sakshamgarg2323/eurosat/train/train/HerbaceousVegetation | Contains 2600 files

In [ ]:
import torch

if torch.cuda.is_available():
    print(f"GPU Connected: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not detected. Please check Accelerator settings.")

GPU Connected: Tesla T4

**Here is the code for Fine tuning the model**

In [ ]:
import os
import sys
import torch
from torch import nn
from torch.utils.data import DataLoader, Subset
from torchvision.transforms import v2
from PIL import Image
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

In [ ]:
# setting up the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# defining the class mappings, could have been done simply by using image folders but forgot to do that
Class_Mapping = {
    'AnnualCrop': 0, 'Forest': 1, 'HerbaceousVegetation': 2,
    'Highway': 3, 'Industrial': 4, 'Pasture': 5,
    'PermanentCrop': 6, 'Residential': 7, 'River': 8, 'SeaLake': 9
}
# 1. Update the base path variable
base_path = '/kaggle/input/datasets/sakshamgarg2323/eurosat'

train_dir = os.path.join(base_path, 'train', 'train')
test_dir = os.path.join(base_path, 'test_set', 'test_set')

Using device: cuda

In [ ]:
class EuroSATLabeled(torch.utils.data.Dataset):
    def __init__(self, img_dir, transforms=None):
        self.img_dir = img_dir
        self.transforms = transforms
        self.data = []
        for class_name in os.listdir(self.img_dir):
            class_path = os.path.join(self.img_dir, class_name)
            if os.path.isdir(class_path):
                class_label = Class_Mapping[class_name]
                for img_name in os.listdir(class_path):
                      self.data.append((os.path.join(class_path, img_name), class_label, img_name))

    def __len__(self): return len(self.data)

    def __getitem__(self, idx):
        img_path, class_label, img_filename = self.data[idx]
        img = Image.open(img_path).convert('RGB')
        if self.transforms:
            img = self.transforms(img)
        return img, class_label, img_filename

class EuroSATUnlabeled(torch.utils.data.Dataset):
    def __init__(self, img_dir, transforms=None):
        self.img_dir = img_dir
        self.transforms = transforms
        self.data = []
        for img_name in os.listdir(self.img_dir):
              self.data.append((os.path.join(self.img_dir, img_name), img_name))

    def __len__(self): return len(self.data)

    def __getitem__(self, idx):
        img_path, img_filename = self.data[idx]
        img = Image.open(img_path).convert('RGB')
        if self.transforms:
            img = self.transforms(img)
        return img, img_filename

In [ ]:
EUROSAT_MEAN = [0.3444, 0.3803, 0.4078]
EUROSAT_STD  = [0.2025, 0.1366, 0.1148]
train_transforms = v2.Compose([
    v2.Resize((224,224), antialias=True),              # slightly larger before crop
    v2.RandomHorizontalFlip(p=0.5),
    v2.RandomVerticalFlip(p=0.5),
    v2.RandomApply([v2.RandomRotation(degrees=(90, 90))], p=0.5),   # only 90° multiples
    v2.RandomApply([v2.RandomRotation(degrees=(180, 180))], p=0.25),
    v2.ToImage(),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=EUROSAT_MEAN, std=EUROSAT_STD),
])

test_transforms = v2.Compose([
    v2.Resize((224, 224), antialias=True),   # ← same fix here
    v2.ToImage(),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=EUROSAT_MEAN, std=EUROSAT_STD),
])
tta_transform = v2.Compose([
    v2.Resize((224, 224), antialias=True),
    v2.RandomHorizontalFlip(p=0.5),
    v2.RandomVerticalFlip(p=0.5),
    # Restrict to 90/180/270 rotations to prevent black zero-padding
    v2.RandomApply([v2.RandomRotation(degrees=(90, 90))], p=0.5),
    v2.RandomApply([v2.RandomRotation(degrees=(180, 180))], p=0.25),
    v2.RandomApply([v2.RandomRotation(degrees=(270, 270))], p=0.25),
    v2.ToImage(),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=EUROSAT_MEAN, std=EUROSAT_STD),
])

# 3. Now initialize your datasets
full_train_aug = EuroSATLabeled(img_dir=train_dir, transforms=train_transforms)
full_train_no_aug = EuroSATLabeled(img_dir=train_dir, transforms=test_transforms)
test_dataset = EuroSATUnlabeled(img_dir=test_dir, transforms=test_transforms)
#class for preprocessing of labelled data from train.zip

targets = [item[1] for item in full_train_aug.data]
indices = list(range(len(full_train_aug)))

train_indices, val_indices = train_test_split(
    indices, test_size=0.2, stratify=targets, random_state=42
)

train_dataset = Subset(full_train_aug, train_indices)
val_dataset = Subset(full_train_no_aug, val_indices)
test_dataset = EuroSATUnlabeled(
    img_dir=test_dir,
    transforms=test_transforms
)
# Validation TTA loader (uses same val_indices split)
tta_val_base    = EuroSATLabeled(img_dir=train_dir, transforms=tta_transform)
tta_val_dataset = Subset(tta_val_base, val_indices)
tta_val_loader  = DataLoader(tta_val_dataset, batch_size=256, shuffle=False,
                             num_workers=4, pin_memory=True, persistent_workers=True)
batch_size = 256
# Test TTA loader (for submission)
tta_test_dataset = EuroSATUnlabeled(img_dir=test_dir, transforms=tta_transform)
tta_test_loader  = DataLoader(tta_test_dataset, batch_size=256, shuffle=False,
                              num_workers=4, pin_memory=True, persistent_workers=True)

In [ ]:
batch_size = 256

# --- [UPDATED] Hardware Acceleration for DataLoaders ---
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True,persistent_workers=True)
val_dataloader = DataLoader(
    val_dataset, batch_size=batch_size, shuffle=False,
    num_workers=4, pin_memory=True, persistent_workers=True   # ← was missing
)
test_dataloader = DataLoader(
    test_dataset, batch_size=batch_size, shuffle=False,
    num_workers=4, pin_memory=True, persistent_workers=True
)

print(f"Training samples: {len(train_dataset)}")
print(f"Validation samples: {len(val_dataset)}")
print(f"Submission samples: {len(test_dataset)}")

Training samples: 18400
Validation samples: 4600
Submission samples: 4000

In [ ]:
# import torch.nn.functional as F

# class BasicBlock(nn.Module):
#     expansion = 1
#     def __init__(self, in_channels, out_channels, stride=1):
#         super(BasicBlock, self).__init__()
#         self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
#         self.bn1 = nn.BatchNorm2d(out_channels)
#         self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False)
#         self.bn2 = nn.BatchNorm2d(out_channels)
#         self.shortcut = nn.Sequential()
#         if stride != 1 or in_channels != self.expansion * out_channels:
#             self.shortcut = nn.Sequential(
#                 nn.Conv2d(in_channels, self.expansion * out_channels, kernel_size=1, stride=stride, bias=False),
#                 nn.BatchNorm2d(self.expansion * out_channels)
#             )

#     def forward(self, x):
#         out = F.relu(self.bn1(self.conv1(x)))
#         out = self.bn2(self.conv2(out))
#         out += self.shortcut(x)
#         out = F.relu(out)
#         return out
# class Bottleneck(nn.Module):
#     expansion = 4 # This is crucial: Bottleneck increases out_channels by 4x

#     def __init__(self, in_channels, out_channels, stride=1):
#         super(Bottleneck, self).__init__()
#         # 1x1 conv to compress channels
#         self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=1, bias=False)
#         self.bn1 = nn.BatchNorm2d(out_channels)

#         # 3x3 conv
#         self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
#         self.bn2 = nn.BatchNorm2d(out_channels)

#         # 1x1 conv to expand channels back out
#         self.conv3 = nn.Conv2d(out_channels, self.expansion * out_channels, kernel_size=1, bias=False)
#         self.bn3 = nn.BatchNorm2d(self.expansion * out_channels)

#         self.shortcut = nn.Sequential()
#         if stride != 1 or in_channels != self.expansion * out_channels:
#             self.shortcut = nn.Sequential(
#                 nn.Conv2d(in_channels, self.expansion * out_channels, kernel_size=1, stride=stride, bias=False),
#                 nn.BatchNorm2d(self.expansion * out_channels)
#             )

#     def forward(self, x):
#         out = F.relu(self.bn1(self.conv1(x)))
#         out = F.relu(self.bn2(self.conv2(out)))
#         out = self.bn3(self.conv3(out))
#         out += self.shortcut(x)
#         out = F.relu(out)
#         return out

# class ResNet(nn.Module):
#     def __init__(self, block, num_blocks, num_classes=10):
#         super(ResNet, self).__init__()
#         self.in_channels = 64
#         self.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
#         self.bn1 = nn.BatchNorm2d(64)

#         self.layer1 = self._make_layer(block, 64, num_blocks[0], stride=1)
#         self.layer2 = self._make_layer(block, 128, num_blocks[1], stride=2)
#         self.layer3 = self._make_layer(block, 256, num_blocks[2], stride=2)
#         self.layer4 = self._make_layer(block, 512, num_blocks[3], stride=2)

#         self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
#         self.linear = nn.Linear(512 * block.expansion, num_classes)

#     def _make_layer(self, block, out_channels, num_blocks, stride):
#         strides = [stride] + [1] * (num_blocks - 1)
#         layers = []
#         for s in strides:
#             layers.append(block(self.in_channels, out_channels, s))
#             self.in_channels = out_channels * block.expansion
#         return nn.Sequential(*layers)

#     def forward(self, x):
#         out = F.relu(self.bn1(self.conv1(x)))
#         out = self.layer1(out)
#         out = self.layer2(out)
#         out = self.layer3(out)
#         out = self.layer4(out)
#         out = self.avgpool(out)
#         out = torch.flatten(out, 1)
#         out = self.linear(out)
#         return out

# def build_resnet50_64x64(num_classes):
#     # Change 'BasicBlock' to 'Bottleneck'
#     return ResNet(Bottleneck, [3, 4, 6, 3], num_classes=num_classes)

# model = build_resnet50_64x64(num_classes=len(Class_Mapping)).to(device)

# def init_weights(m):
#     if isinstance(m, nn.Conv2d):
#         nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
#     elif isinstance(m, nn.BatchNorm2d):
#         nn.init.constant_(m.weight, 1)
#         nn.init.constant_(m.bias, 0)


# model.apply(init_weights)
# print("Applied Kaiming Normal initialization.")

In [ ]:
import torchvision.models as models
from torch import nn

# 1. Load the pretrained ResNet-18
model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)

# [REMOVED THE FREEZING LOOP HERE] - The backbone is now fully trainable

# 2. Replace the final linear classification layer
num_ftrs = model.fc.in_features
model.fc = nn.Sequential(
    nn.Linear(num_ftrs, 1024),
    nn.BatchNorm1d(1024),
    nn.LeakyReLU(inplace=True),
    nn.Dropout(p=0.4),
    nn.Linear(1024, 256),
    nn.BatchNorm1d(256),
    nn.ReLU(inplace=True),
    nn.Linear(256, len(Class_Mapping))
)

# Send the model to your configured device (GPU)
model = model.to(device)

print(f"Total parameters: {sum(p.numel() for p in model.parameters())}")
print(f"Trainable parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad)}")
# Trainable parameters should now equal Total parameters!

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth

100%|██████████| 44.7M/44.7M [00:00<00:00, 153MB/s]

Total parameters: 11969354
Trainable parameters: 11969354

In [ ]:
# --- HYPERPARAMETER TUNING FOR FINE-TUNING ---
backbone_lr = 1e-4        # Very gentle learning rate for pretrained weights
head_lr = 1e-3            # Standard learning rate for the new dense layers
weight_decay = 1e-2       # Increased from 1e-3 for better regularization on the whole model
num_epochs = 80           # Fine-tuning converges faster; 50 is plenty
warmup_epochs = 5
early_stop_patience = 80  # Reduced from 80. Fine-tuning overfits faster if unchecked.

class_weights = torch.ones(len(Class_Mapping)).to(device)
class_weights[2] = 1.3  # HerbaceousVegetation
class_weights[5] = 1.6  # Pasture (Smallest class)
class_weights[6] = 1.3  # PermanentCrop

loss_fn = nn.CrossEntropyLoss(weight=class_weights, label_smoothing=0.1)

# 1. Separate parameters into two groups
backbone_params = [p for n, p in model.named_parameters() if not n.startswith('fc')]
head_params = model.fc.parameters()

# 2. Pass both groups to AdamW with their respective learning rates
optimizer = torch.optim.AdamW([
    {'params': backbone_params, 'lr': backbone_lr},
    {'params': head_params, 'lr': head_lr}
], weight_decay=weight_decay, amsgrad=True)

# 3. Schedulers (These will automatically scale both parameter groups proportionally)
warmup_scheduler = torch.optim.lr_scheduler.LinearLR(
    optimizer, start_factor=0.1, end_factor=1.0, total_iters=warmup_epochs
)
cosine_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=num_epochs - warmup_epochs, eta_min=1e-6
)
scheduler = torch.optim.lr_scheduler.SequentialLR(
    optimizer,
    schedulers=[warmup_scheduler, cosine_scheduler],
    milestones=[warmup_epochs]
)

checkpoint_path = '/kaggle/working/EuroSAT_Finetuned_ResNet18.pth'
print("Optimizer and Schedulers configured for Differential Fine-Tuning.")

Optimizer and Schedulers configured for Differential Fine-Tuning.

In [ ]:
import torchvision.transforms.functional as TF

def run_deterministic_tta(model, dataloader, device, labeled=True):
    """
    Runs deterministic 8-way TTA (Dihedral group D4).
    The dataloader passed to this should have NO random augmentations (use test_transforms).
    """
    model.eval()
    n = len(dataloader.dataset)
    acc_prob = torch.zeros(n, len(Class_Mapping))
    labels_out, names_out = [], []

    ptr = 0
    with torch.no_grad():
        for batch in dataloader:
            if labeled:
                X, y, _ = batch
                labels_out.extend(y.tolist())
            else:
                X, names = batch
                names_out.extend(names)

            X = X.to(device)
            batch_size = X.size(0)
            batch_probs = torch.zeros(batch_size, len(Class_Mapping), device=device)

            # The 8 exact symmetry states for a satellite tile
            transforms = [
                lambda x: x,                               # Identity
                lambda x: TF.rotate(x, 90),                # Rot 90
                lambda x: TF.rotate(x, 180),               # Rot 180
                lambda x: TF.rotate(x, 270),               # Rot 270
                lambda x: TF.hflip(x),                     # H-Flip
                lambda x: TF.rotate(TF.hflip(x), 90),      # H-Flip + Rot 90
                lambda x: TF.rotate(TF.hflip(x), 180),     # H-Flip + Rot 180
                lambda x: TF.rotate(TF.hflip(x), 270),     # H-Flip + Rot 270
            ]

            # Accumulate probabilities for all 8 views
            for t in transforms:
                with torch.amp.autocast('cuda'):
                    logits = model(t(X))
                batch_probs += torch.softmax(logits, dim=1)

            batch_probs /= 8.0  # Average before argmax
            acc_prob[ptr:ptr + batch_size] = batch_probs.cpu()
            ptr += batch_size

    preds = acc_prob.argmax(dim=1).numpy()
    return (preds, labels_out) if labeled else (preds, names_out)

In [ ]:
scaler = torch.amp.GradScaler('cuda')
cutmix = v2.CutMix(num_classes=len(Class_Mapping), alpha=1.0)
# cutmix = None
# for m in model.modules():
#         if isinstance(m, nn.BatchNorm2d):
#             m.eval()
import random

scaler = torch.amp.GradScaler('cuda')
cutmix = v2.CutMix(num_classes=len(Class_Mapping), alpha=1.0)

def train_loop(dataloader, model, loss_fn, optimizer, cutmix=None):
    model.train()

    # FIXED: Removed the m.eval() loop for BatchNorm.
    # Let the batch statistics update to match the Sentinel-2 domain!

    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    correct = 0
    running_loss = 0.0

    for batch, (X, y, _) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # FIXED: Probabilistic CutMix (50% chance).
        # This ensures the model still sees clean, whole images during training.
        applied_cutmix = False
        if cutmix is not None and random.random() < 0.5:
            X, y = cutmix(X, y)
            applied_cutmix = True

        optimizer.zero_grad()

        with torch.amp.autocast('cuda'):
            pred = model(X)
            loss = loss_fn(pred, y)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()

        if batch % 10 == 0:
            print(f"loss: {loss.item():>7f}  [{batch * dataloader.batch_size + len(X):>5d}/{size:>5d}]")

        if applied_cutmix:
            correct += (pred.argmax(1) == y.argmax(1)).type(torch.float).sum().item()
        else:
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    train_accuracy = correct / size
    avg_train_loss = running_loss / num_batches

    print(f"Training Accuracy: {100*train_accuracy:.1f}%  Avg Loss: {avg_train_loss:.6f}")
    return train_accuracy, avg_train_loss
def test_loop(dataloader, model, loss_fn):
    model.eval()
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y, _ in dataloader:
            X, y = X.to(device), y.to(device)
            with torch.amp.autocast('cuda'):
                pred = model(X)
                # FIXED: Moved loss calculation inside the autocast block
                # so it handles the float16/float32 mixed precision automatically
                batch_loss = loss_fn(pred, y)

            test_loss += batch_loss.item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    accuracy = correct / size
    print(f"Validation: Accuracy={100*accuracy:.1f}%, Avg Loss={test_loss:.6f}\n")
    return test_loss, accuracy

In [ ]:
history = []
best_vacc = 0.0            # ← was best_vloss = float('inf')
early_stop_counter = 0
start_epoch = 0

for t in range(start_epoch, num_epochs):
    print(f"Epoch {t+1}")
    train_acc, train_loss = train_loop(train_dataloader, model, loss_fn, optimizer, cutmix=cutmix)
    vloss, vacc = test_loop(val_dataloader, model, loss_fn)

    scheduler.step()

    history.append({
        'epoch':      t + 1,
        'train_loss': train_loss,
        'train_acc':  train_acc,
        'val_loss':   vloss,
        'val_acc':    vacc,
        'lr':         scheduler.get_last_lr()[0]
    })

    if vacc > best_vacc:   # ← was: vloss < best_vloss
        print(f"Val accuracy improved {100*best_vacc:.2f}% → {100*vacc:.2f}%. Saving checkpoint...")
        best_vacc = vacc   # ← was: best_vloss = vloss
        early_stop_counter = 0
        torch.save({
            'epoch':           t + 1,
            'model_state':     model.state_dict(),
            'optimizer_state': optimizer.state_dict(),
            'best_vacc':       best_vacc   # ← was: best_vloss
        }, checkpoint_path)
    else:
        early_stop_counter += 1
        print(f"No improvement. Early stop counter: {early_stop_counter}/{early_stop_patience}")
        if early_stop_counter >= early_stop_patience:
            print(f"Early stopping at epoch {t+1}. Best val accuracy: {100*best_vacc:.2f}%")
            break

print(f"\nTraining complete. Best val accuracy: {100*best_vacc:.2f}%")
pd.DataFrame(history)

Epoch 1
loss: 2.568181  [  256/18400]
loss: 1.752754  [ 2816/18400]
loss: 1.375841  [ 5376/18400]
loss: 1.112573  [ 7936/18400]
loss: 1.899470  [10496/18400]
loss: 1.000506  [13056/18400]
loss: 0.917749  [15616/18400]
loss: 0.855736  [18176/18400]
Training Accuracy: 65.0%  Avg Loss: 1.582058
Validation: Accuracy=90.8%, Avg Loss=0.815420

Val accuracy improved 0.00% → 90.78%. Saving checkpoint...
Epoch 2
loss: 0.840035  [  256/18400]
loss: 1.031542  [ 2816/18400]
loss: 0.687248  [ 5376/18400]
loss: 1.569940  [ 7936/18400]
loss: 0.672186  [10496/18400]
loss: 0.662790  [13056/18400]
loss: 1.397047  [15616/18400]
loss: 0.664032  [18176/18400]
Training Accuracy: 85.4%  Avg Loss: 1.120469
Validation: Accuracy=95.8%, Avg Loss=0.670067

Val accuracy improved 90.78% → 95.80%. Saving checkpoint...
Epoch 3
loss: 0.646290  [  256/18400]
loss: 1.504937  [ 2816/18400]
loss: 0.620179  [ 5376/18400]
loss: 0.651376  [ 7936/18400]
loss: 0.653669  [10496/18400]
loss: 0.608741  [13056/18400]
loss: 0.598404  [15616/18400]
loss: 0.612789  [18176/18400]
Training Accuracy: 89.7%  Avg Loss: 0.970350
Validation: Accuracy=97.4%, Avg Loss=0.623562

Val accuracy improved 95.80% → 97.41%. Saving checkpoint...
Epoch 4
loss: 0.588971  [  256/18400]
loss: 0.582094  [ 2816/18400]
loss: 1.171605  [ 5376/18400]
loss: 1.241102  [ 7936/18400]
loss: 0.884735  [10496/18400]
loss: 0.579462  [13056/18400]
loss: 1.457406  [15616/18400]
loss: 1.185328  [18176/18400]
Training Accuracy: 91.5%  Avg Loss: 0.955934
Validation: Accuracy=97.0%, Avg Loss=0.625930

No improvement. Early stop counter: 1/80
Epoch 5
loss: 1.207988  [  256/18400]
loss: 0.597584  [ 2816/18400]
loss: 1.385387  [ 5376/18400]
loss: 0.748030  [ 7936/18400]
loss: 1.463080  [10496/18400]
loss: 1.339650  [13056/18400]
loss: 1.345446  [15616/18400]
loss: 0.562646  [18176/18400]
Training Accuracy: 90.8%  Avg Loss: 0.896828
Validation: Accuracy=98.0%, Avg Loss=0.566964

Val accuracy improved 97.41% → 97.98%. Saving checkpoint...
Epoch 6
loss: 1.209730  [  256/18400]
loss: 1.106386  [ 2816/18400]
loss: 1.056159  [ 5376/18400]
loss: 1.130282  [ 7936/18400]
loss: 0.560099  [10496/18400]
loss: 0.582699  [13056/18400]
loss: 0.578855  [15616/18400]
loss: 0.563110  [18176/18400]
Training Accuracy: 92.7%  Avg Loss: 0.878067
Validation: Accuracy=97.5%, Avg Loss=0.582896

No improvement. Early stop counter: 1/80
Epoch 7
loss: 0.558342  [  256/18400]
loss: 1.326063  [ 2816/18400]
loss: 0.542486  [ 5376/18400]
loss: 0.773351  [ 7936/18400]
loss: 1.211570  [10496/18400]
loss: 0.563974  [13056/18400]
loss: 0.552497  [15616/18400]
loss: 1.323827  [18176/18400]
Training Accuracy: 92.7%  Avg Loss: 0.880395
Validation: Accuracy=98.3%, Avg Loss=0.565974

Val accuracy improved 97.98% → 98.33%. Saving checkpoint...
Epoch 8
loss: 0.549464  [  256/18400]
loss: 0.540855  [ 2816/18400]
loss: 0.571257  [ 5376/18400]
loss: 0.565660  [ 7936/18400]
loss: 0.558953  [10496/18400]
loss: 1.191963  [13056/18400]
loss: 1.283489  [15616/18400]
loss: 1.240092  [18176/18400]
Training Accuracy: 91.8%  Avg Loss: 0.846644
Validation: Accuracy=97.9%, Avg Loss=0.568139

No improvement. Early stop counter: 1/80
Epoch 9
loss: 0.545512  [  256/18400]
loss: 0.531835  [ 2816/18400]
loss: 0.932615  [ 5376/18400]
loss: 1.115488  [ 7936/18400]
loss: 0.974115  [10496/18400]
loss: 1.264316  [13056/18400]
loss: 1.124424  [15616/18400]
loss: 0.537056  [18176/18400]
Training Accuracy: 95.7%  Avg Loss: 0.792909
Validation: Accuracy=98.2%, Avg Loss=0.560629

No improvement. Early stop counter: 2/80
Epoch 10
loss: 1.135460  [  256/18400]
loss: 1.343177  [ 2816/18400]
loss: 0.787085  [ 5376/18400]
loss: 1.293947  [ 7936/18400]
loss: 0.564708  [10496/18400]
loss: 0.557799  [13056/18400]
loss: 0.528225  [15616/18400]
loss: 1.257140  [18176/18400]
Training Accuracy: 94.0%  Avg Loss: 0.818057
Validation: Accuracy=98.0%, Avg Loss=0.564698

No improvement. Early stop counter: 3/80
Epoch 11
loss: 1.282750  [  256/18400]
loss: 0.928389  [ 2816/18400]
loss: 0.850763  [ 5376/18400]
loss: 1.070914  [ 7936/18400]
loss: 0.553010  [10496/18400]
loss: 1.303732  [13056/18400]
loss: 0.544236  [15616/18400]
loss: 1.154536  [18176/18400]
Training Accuracy: 90.2%  Avg Loss: 0.895744
Validation: Accuracy=97.9%, Avg Loss=0.583217

No improvement. Early stop counter: 4/80
Epoch 12
loss: 0.539680  [  256/18400]
loss: 0.527190  [ 2816/18400]
loss: 0.541353  [ 5376/18400]
loss: 1.213906  [ 7936/18400]
loss: 0.538808  [10496/18400]
loss: 0.520593  [13056/18400]
loss: 0.540388  [15616/18400]
loss: 1.130248  [18176/18400]
Training Accuracy: 93.6%  Avg Loss: 0.807122
Validation: Accuracy=97.9%, Avg Loss=0.568191

No improvement. Early stop counter: 5/80
Epoch 13
loss: 0.528742  [  256/18400]
loss: 0.551659  [ 2816/18400]
loss: 0.534945  [ 5376/18400]
loss: 0.552293  [ 7936/18400]
loss: 0.562421  [10496/18400]
loss: 0.518627  [13056/18400]
loss: 0.717884  [15616/18400]
loss: 1.074513  [18176/18400]
Training Accuracy: 92.0%  Avg Loss: 0.822673
Validation: Accuracy=98.5%, Avg Loss=0.559582

Val accuracy improved 98.33% → 98.46%. Saving checkpoint...
Epoch 14
loss: 1.293685  [  256/18400]
loss: 1.170424  [ 2816/18400]
loss: 0.540174  [ 5376/18400]
loss: 0.534064  [ 7936/18400]
loss: 0.532305  [10496/18400]
loss: 1.246803  [13056/18400]
loss: 0.958304  [15616/18400]
loss: 1.009361  [18176/18400]
Training Accuracy: 93.9%  Avg Loss: 0.829683
Validation: Accuracy=98.3%, Avg Loss=0.558408

No improvement. Early stop counter: 1/80
Epoch 15
loss: 0.528966  [  256/18400]
loss: 0.534336  [ 2816/18400]
loss: 0.543348  [ 5376/18400]
loss: 0.519993  [ 7936/18400]
loss: 1.249472  [10496/18400]
loss: 0.856444  [13056/18400]
loss: 0.531353  [15616/18400]
loss: 1.222188  [18176/18400]
Training Accuracy: 92.1%  Avg Loss: 0.865099
Validation: Accuracy=98.1%, Avg Loss=0.554274

No improvement. Early stop counter: 2/80
Epoch 16
loss: 0.530455  [  256/18400]
loss: 0.527289  [ 2816/18400]
loss: 1.085728  [ 5376/18400]
loss: 0.527187  [ 7936/18400]
loss: 0.523561  [10496/18400]
loss: 1.257090  [13056/18400]
loss: 1.101283  [15616/18400]
loss: 1.215386  [18176/18400]
Training Accuracy: 93.9%  Avg Loss: 0.834885
Validation: Accuracy=98.3%, Avg Loss=0.561075

No improvement. Early stop counter: 3/80
Epoch 17
loss: 0.663344  [  256/18400]
loss: 1.236861  [ 2816/18400]
loss: 0.526963  [ 5376/18400]
loss: 0.522076  [ 7936/18400]
loss: 1.240713  [10496/18400]
loss: 0.525859  [13056/18400]
loss: 0.823209  [15616/18400]
loss: 1.056499  [18176/18400]
Training Accuracy: 92.5%  Avg Loss: 0.816449
Validation: Accuracy=98.0%, Avg Loss=0.570441

No improvement. Early stop counter: 4/80
Epoch 18
loss: 0.538399  [  256/18400]
loss: 0.515669  [ 2816/18400]
loss: 0.727245  [ 5376/18400]
loss: 1.091464  [ 7936/18400]
loss: 0.516120  [10496/18400]
loss: 0.526525  [13056/18400]
loss: 0.527274  [15616/18400]
loss: 1.224269  [18176/18400]
Training Accuracy: 93.7%  Avg Loss: 0.815765
Validation: Accuracy=98.7%, Avg Loss=0.546796

Val accuracy improved 98.46% → 98.70%. Saving checkpoint...
Epoch 19
loss: 0.520465  [  256/18400]
loss: 0.521053  [ 2816/18400]
loss: 1.170254  [ 5376/18400]
loss: 1.124477  [ 7936/18400]
loss: 0.958030  [10496/18400]
loss: 0.524246  [13056/18400]
loss: 1.148689  [15616/18400]
loss: 1.055711  [18176/18400]
Training Accuracy: 94.5%  Avg Loss: 0.836922
Validation: Accuracy=98.3%, Avg Loss=0.556861

No improvement. Early stop counter: 1/80
Epoch 20
loss: 1.169057  [  256/18400]
loss: 1.144097  [ 2816/18400]
loss: 1.220793  [ 5376/18400]
loss: 0.520377  [ 7936/18400]
loss: 1.015946  [10496/18400]
loss: 1.218538  [13056/18400]
loss: 0.513731  [15616/18400]
loss: 0.515587  [18176/18400]
Training Accuracy: 92.6%  Avg Loss: 0.861887
Validation: Accuracy=98.5%, Avg Loss=0.555555

No improvement. Early stop counter: 2/80
Epoch 21
loss: 1.058795  [  256/18400]
loss: 0.516645  [ 2816/18400]
loss: 1.050832  [ 5376/18400]
loss: 0.975722  [ 7936/18400]
loss: 1.191633  [10496/18400]
loss: 0.527455  [13056/18400]
loss: 1.176886  [15616/18400]
loss: 0.549122  [18176/18400]
Training Accuracy: 94.5%  Avg Loss: 0.825881
Validation: Accuracy=98.4%, Avg Loss=0.547279

No improvement. Early stop counter: 3/80
Epoch 22
loss: 0.864737  [  256/18400]
loss: 1.199249  [ 2816/18400]
loss: 0.772525  [ 5376/18400]
loss: 1.182724  [ 7936/18400]
loss: 0.501373  [10496/18400]
loss: 0.549899  [13056/18400]
loss: 0.506900  [15616/18400]
loss: 1.086185  [18176/18400]
Training Accuracy: 93.0%  Avg Loss: 0.835498
Validation: Accuracy=98.6%, Avg Loss=0.556975

No improvement. Early stop counter: 4/80
Epoch 23
loss: 1.205145  [  256/18400]
loss: 1.164030  [ 2816/18400]
loss: 0.541408  [ 5376/18400]
loss: 1.251968  [ 7936/18400]
loss: 0.514913  [10496/18400]
loss: 1.220786  [13056/18400]
loss: 0.527534  [15616/18400]
loss: 0.543482  [18176/18400]
Training Accuracy: 95.3%  Avg Loss: 0.787496
Validation: Accuracy=98.7%, Avg Loss=0.544809

No improvement. Early stop counter: 5/80
Epoch 24
loss: 0.529542  [  256/18400]
loss: 0.511131  [ 2816/18400]
loss: 0.514128  [ 5376/18400]
loss: 0.522213  [ 7936/18400]
loss: 1.255132  [10496/18400]
loss: 0.514564  [13056/18400]
loss: 1.240285  [15616/18400]
loss: 1.196858  [18176/18400]
Training Accuracy: 92.9%  Avg Loss: 0.841104
Validation: Accuracy=98.5%, Avg Loss=0.555203

No improvement. Early stop counter: 6/80
Epoch 25
loss: 0.533689  [  256/18400]
loss: 1.184522  [ 2816/18400]
loss: 0.520794  [ 5376/18400]
loss: 1.174037  [ 7936/18400]
loss: 0.507953  [10496/18400]
loss: 0.515135  [13056/18400]
loss: 0.518282  [15616/18400]
loss: 0.510321  [18176/18400]
Training Accuracy: 92.3%  Avg Loss: 0.828726
Validation: Accuracy=98.7%, Avg Loss=0.545129

No improvement. Early stop counter: 7/80
Epoch 26
loss: 0.526079  [  256/18400]
loss: 0.510452  [ 2816/18400]
loss: 0.512854  [ 5376/18400]
loss: 0.534336  [ 7936/18400]
loss: 1.233346  [10496/18400]
loss: 1.103125  [13056/18400]
loss: 1.152317  [15616/18400]
loss: 1.178489  [18176/18400]
Training Accuracy: 95.7%  Avg Loss: 0.790552
Validation: Accuracy=98.6%, Avg Loss=0.552247

No improvement. Early stop counter: 8/80
Epoch 27
loss: 0.510100  [  256/18400]
loss: 0.532273  [ 2816/18400]
loss: 0.519251  [ 5376/18400]
loss: 1.129271  [ 7936/18400]
loss: 0.893559  [10496/18400]
loss: 0.507786  [13056/18400]
loss: 0.785547  [15616/18400]
loss: 0.519680  [18176/18400]
Training Accuracy: 94.6%  Avg Loss: 0.789742
Validation: Accuracy=98.4%, Avg Loss=0.553008

No improvement. Early stop counter: 9/80
Epoch 28
loss: 1.078378  [  256/18400]
loss: 0.522033  [ 2816/18400]
loss: 0.520343  [ 5376/18400]
loss: 1.090713  [ 7936/18400]
loss: 0.783854  [10496/18400]
loss: 1.065340  [13056/18400]
loss: 0.512962  [15616/18400]
loss: 0.517137  [18176/18400]
Training Accuracy: 92.3%  Avg Loss: 0.825160
Validation: Accuracy=98.7%, Avg Loss=0.544369

Val accuracy improved 98.70% → 98.74%. Saving checkpoint...
Epoch 29
loss: 1.162493  [  256/18400]
loss: 0.511053  [ 2816/18400]
loss: 0.518192  [ 5376/18400]
loss: 0.990009  [ 7936/18400]
loss: 1.082583  [10496/18400]
loss: 0.518626  [13056/18400]
loss: 0.514755  [15616/18400]
loss: 0.509535  [18176/18400]
Training Accuracy: 96.4%  Avg Loss: 0.762078
Validation: Accuracy=98.8%, Avg Loss=0.540277

Val accuracy improved 98.74% → 98.78%. Saving checkpoint...
Epoch 30
loss: 1.207627  [  256/18400]
loss: 0.524936  [ 2816/18400]
loss: 0.519146  [ 5376/18400]
loss: 0.885765  [ 7936/18400]
loss: 1.167599  [10496/18400]
loss: 0.519924  [13056/18400]
loss: 0.507665  [15616/18400]
loss: 0.512555  [18176/18400]
Training Accuracy: 95.9%  Avg Loss: 0.776517
Validation: Accuracy=98.7%, Avg Loss=0.542843

No improvement. Early stop counter: 1/80
Epoch 31
loss: 1.004911  [  256/18400]
loss: 1.208209  [ 2816/18400]
loss: 0.524793  [ 5376/18400]
loss: 1.119794  [ 7936/18400]
loss: 0.507387  [10496/18400]
loss: 0.796291  [13056/18400]
loss: 0.538599  [15616/18400]
loss: 1.188198  [18176/18400]
Training Accuracy: 94.4%  Avg Loss: 0.800370
Validation: Accuracy=98.6%, Avg Loss=0.542807

No improvement. Early stop counter: 2/80
Epoch 32
loss: 0.510920  [  256/18400]
loss: 0.912997  [ 2816/18400]
loss: 0.911511  [ 5376/18400]
loss: 0.515503  [ 7936/18400]
loss: 1.164370  [10496/18400]
loss: 0.518844  [13056/18400]
loss: 0.523160  [15616/18400]
loss: 1.244990  [18176/18400]
Training Accuracy: 94.9%  Avg Loss: 0.789736
Validation: Accuracy=98.8%, Avg Loss=0.542030

Val accuracy improved 98.78% → 98.80%. Saving checkpoint...
Epoch 33
loss: 1.103269  [  256/18400]
loss: 0.843516  [ 2816/18400]
loss: 0.754263  [ 5376/18400]
loss: 0.506727  [ 7936/18400]
loss: 0.527901  [10496/18400]
loss: 1.147961  [13056/18400]
loss: 0.514772  [15616/18400]
loss: 1.059976  [18176/18400]
Training Accuracy: 94.8%  Avg Loss: 0.791288
Validation: Accuracy=98.7%, Avg Loss=0.542823

No improvement. Early stop counter: 1/80
Epoch 34
loss: 0.908643  [  256/18400]
loss: 1.191769  [ 2816/18400]
loss: 0.515630  [ 5376/18400]
loss: 1.202353  [ 7936/18400]
loss: 0.507828  [10496/18400]
loss: 1.242329  [13056/18400]
loss: 0.510138  [15616/18400]
loss: 1.082070  [18176/18400]
Training Accuracy: 95.3%  Avg Loss: 0.824965
Validation: Accuracy=98.8%, Avg Loss=0.545826

No improvement. Early stop counter: 2/80
Epoch 35
loss: 0.860006  [  256/18400]
loss: 1.153707  [ 2816/18400]
loss: 0.514402  [ 5376/18400]
loss: 0.513206  [ 7936/18400]
loss: 0.512573  [10496/18400]
loss: 0.911932  [13056/18400]
loss: 0.510629  [15616/18400]
loss: 1.181945  [18176/18400]
Training Accuracy: 96.4%  Avg Loss: 0.747656
Validation: Accuracy=98.8%, Avg Loss=0.540765

Val accuracy improved 98.80% → 98.85%. Saving checkpoint...
Epoch 36
loss: 1.097519  [  256/18400]
loss: 1.246634  [ 2816/18400]
loss: 1.196941  [ 5376/18400]
loss: 0.953907  [ 7936/18400]
loss: 1.166082  [10496/18400]
loss: 1.204674  [13056/18400]
loss: 1.120902  [15616/18400]
loss: 1.203621  [18176/18400]
Training Accuracy: 95.9%  Avg Loss: 0.764473
Validation: Accuracy=98.7%, Avg Loss=0.547307

No improvement. Early stop counter: 1/80
Epoch 37
loss: 1.228065  [  256/18400]
loss: 1.218637  [ 2816/18400]
loss: 1.186753  [ 5376/18400]
loss: 0.514343  [ 7936/18400]
loss: 0.514422  [10496/18400]
loss: 0.818224  [13056/18400]
loss: 0.534395  [15616/18400]
loss: 1.177272  [18176/18400]
Training Accuracy: 95.3%  Avg Loss: 0.813146
Validation: Accuracy=98.7%, Avg Loss=0.543425

No improvement. Early stop counter: 2/80
Epoch 38
loss: 1.211131  [  256/18400]
loss: 1.205988  [ 2816/18400]
loss: 1.153940  [ 5376/18400]
loss: 0.507015  [ 7936/18400]
loss: 0.514011  [10496/18400]
loss: 0.525504  [13056/18400]
loss: 0.648637  [15616/18400]
loss: 0.504319  [18176/18400]
Training Accuracy: 95.5%  Avg Loss: 0.783982
Validation: Accuracy=98.8%, Avg Loss=0.542371

No improvement. Early stop counter: 3/80
Epoch 39
loss: 0.517898  [  256/18400]
loss: 1.134897  [ 2816/18400]
loss: 0.506691  [ 5376/18400]
loss: 0.497826  [ 7936/18400]
loss: 1.026006  [10496/18400]
loss: 1.189643  [13056/18400]
loss: 0.508245  [15616/18400]
loss: 0.837864  [18176/18400]
Training Accuracy: 95.2%  Avg Loss: 0.791048
Validation: Accuracy=98.8%, Avg Loss=0.542500

No improvement. Early stop counter: 4/80
Epoch 40
loss: 0.661467  [  256/18400]
loss: 0.930763  [ 2816/18400]
loss: 0.514167  [ 5376/18400]
loss: 0.519427  [ 7936/18400]
loss: 0.769334  [10496/18400]
loss: 0.512382  [13056/18400]
loss: 0.982859  [15616/18400]
loss: 0.511984  [18176/18400]
Training Accuracy: 97.1%  Avg Loss: 0.790250
Validation: Accuracy=98.7%, Avg Loss=0.539870

No improvement. Early stop counter: 5/80
Epoch 41
loss: 1.182773  [  256/18400]
loss: 0.935693  [ 2816/18400]
loss: 1.129810  [ 5376/18400]
loss: 0.516140  [ 7936/18400]
loss: 0.511541  [10496/18400]
loss: 0.522548  [13056/18400]
loss: 0.513330  [15616/18400]
loss: 0.516333  [18176/18400]
Training Accuracy: 95.8%  Avg Loss: 0.757037
Validation: Accuracy=98.7%, Avg Loss=0.540789

No improvement. Early stop counter: 6/80
Epoch 42
loss: 1.045679  [  256/18400]
loss: 0.936813  [ 2816/18400]
loss: 0.513886  [ 5376/18400]
loss: 1.123244  [ 7936/18400]
loss: 0.516245  [10496/18400]
loss: 0.506855  [13056/18400]
loss: 0.510763  [15616/18400]
loss: 1.115038  [18176/18400]
Training Accuracy: 94.0%  Avg Loss: 0.798802
Validation: Accuracy=98.7%, Avg Loss=0.546798

No improvement. Early stop counter: 7/80
Epoch 43
loss: 1.110114  [  256/18400]
loss: 0.506723  [ 2816/18400]
loss: 0.509291  [ 5376/18400]
loss: 0.506463  [ 7936/18400]
loss: 0.511563  [10496/18400]
loss: 1.208754  [13056/18400]
loss: 0.512070  [15616/18400]
loss: 1.065923  [18176/18400]
Training Accuracy: 91.6%  Avg Loss: 0.811754
Validation: Accuracy=98.8%, Avg Loss=0.543565

No improvement. Early stop counter: 8/80
Epoch 44
loss: 1.042771  [  256/18400]
loss: 1.170826  [ 2816/18400]
loss: 0.964121  [ 5376/18400]
loss: 0.514138  [ 7936/18400]
loss: 0.512402  [10496/18400]
loss: 1.115639  [13056/18400]
loss: 1.074102  [15616/18400]
loss: 1.187278  [18176/18400]
Training Accuracy: 94.5%  Avg Loss: 0.794935
Validation: Accuracy=98.8%, Avg Loss=0.545093

No improvement. Early stop counter: 9/80
Epoch 45
loss: 0.975506  [  256/18400]
loss: 0.510702  [ 2816/18400]
loss: 0.506858  [ 5376/18400]
loss: 1.120747  [ 7936/18400]
loss: 1.099329  [10496/18400]
loss: 0.675107  [13056/18400]
loss: 0.510503  [15616/18400]
loss: 0.515750  [18176/18400]
Training Accuracy: 95.3%  Avg Loss: 0.801287
Validation: Accuracy=98.9%, Avg Loss=0.537803

Val accuracy improved 98.85% → 98.91%. Saving checkpoint...
Epoch 46
loss: 0.506338  [  256/18400]
loss: 0.507311  [ 2816/18400]
loss: 0.975232  [ 5376/18400]
loss: 1.186705  [ 7936/18400]
loss: 0.512805  [10496/18400]
loss: 1.168678  [13056/18400]
loss: 1.000459  [15616/18400]
loss: 0.509448  [18176/18400]
Training Accuracy: 93.5%  Avg Loss: 0.818919
Validation: Accuracy=98.8%, Avg Loss=0.540644

No improvement. Early stop counter: 1/80
Epoch 47
loss: 1.148098  [  256/18400]
loss: 1.256354  [ 2816/18400]
loss: 1.227694  [ 5376/18400]
loss: 1.063112  [ 7936/18400]
loss: 0.508710  [10496/18400]
loss: 1.200887  [13056/18400]
loss: 0.512296  [15616/18400]
loss: 1.189749  [18176/18400]
Training Accuracy: 93.6%  Avg Loss: 0.843760
Validation: Accuracy=98.8%, Avg Loss=0.539278

No improvement. Early stop counter: 2/80
Epoch 48
loss: 0.517547  [  256/18400]
loss: 0.997669  [ 2816/18400]
loss: 0.516169  [ 5376/18400]
loss: 0.509888  [ 7936/18400]
loss: 0.503069  [10496/18400]
loss: 1.197954  [13056/18400]
loss: 1.179110  [15616/18400]
loss: 1.045798  [18176/18400]
Training Accuracy: 96.9%  Avg Loss: 0.778172
Validation: Accuracy=98.7%, Avg Loss=0.544076

No improvement. Early stop counter: 3/80
Epoch 49
loss: 0.511394  [  256/18400]
loss: 0.508100  [ 2816/18400]
loss: 0.509102  [ 5376/18400]
loss: 0.506343  [ 7936/18400]
loss: 1.166879  [10496/18400]
loss: 1.088471  [13056/18400]
loss: 0.516333  [15616/18400]
loss: 1.134788  [18176/18400]
Training Accuracy: 96.9%  Avg Loss: 0.793839
Validation: Accuracy=98.9%, Avg Loss=0.539404

No improvement. Early stop counter: 4/80
Epoch 50
loss: 0.499057  [  256/18400]
loss: 1.180239  [ 2816/18400]
loss: 0.514239  [ 5376/18400]
loss: 1.081415  [ 7936/18400]
loss: 0.514171  [10496/18400]
loss: 0.501241  [13056/18400]
loss: 1.208831  [15616/18400]
loss: 0.505453  [18176/18400]
Training Accuracy: 94.8%  Avg Loss: 0.759038
Validation: Accuracy=98.7%, Avg Loss=0.539736

No improvement. Early stop counter: 5/80
Epoch 51
loss: 0.507946  [  256/18400]
loss: 0.506823  [ 2816/18400]
loss: 0.508936  [ 5376/18400]
loss: 0.515949  [ 7936/18400]
loss: 1.171520  [10496/18400]
loss: 1.141984  [13056/18400]
loss: 0.503806  [15616/18400]
loss: 0.514151  [18176/18400]
Training Accuracy: 95.4%  Avg Loss: 0.795401
Validation: Accuracy=98.9%, Avg Loss=0.538651

No improvement. Early stop counter: 6/80
Epoch 52
loss: 0.514193  [  256/18400]
loss: 0.506539  [ 2816/18400]
loss: 1.157334  [ 5376/18400]
loss: 1.156325  [ 7936/18400]
loss: 1.196490  [10496/18400]
loss: 1.132141  [13056/18400]
loss: 0.967889  [15616/18400]
loss: 0.504388  [18176/18400]
Training Accuracy: 95.8%  Avg Loss: 0.754507

    epoch  train_loss  train_acc  val_loss   val_acc        lr
0       1    1.582058   0.650054  0.815420  0.907826  0.000028
1       2    1.120469   0.854457  0.670067  0.958043  0.000046
2       3    0.970350   0.897283  0.623562  0.974130  0.000064
3       4    0.955934   0.914728  0.625930  0.969783  0.000082
4       5    0.896828   0.907772  0.566964  0.979783  0.000100
..    ...         ...        ...       ...       ...       ...
75     76    0.769695   0.963696  0.538835  0.988261  0.000002
76     77    0.766251   0.976957  0.537559  0.988913  0.000001
77     78    0.752859   0.965598  0.537118  0.988696  0.000001
78     79    0.772886   0.966685  0.537670  0.988696  0.000001
79     80    0.686981   0.969293  0.536260  0.987826  0.000001

[80 rows x 6 columns]

In [ ]:
# --- Load best checkpoint ---
print("Loading best checkpoint...")
model_path =checkpoint_path

# 1. Load the checkpoint file
checkpoint = torch.load(model_path, map_location=device)

# 2. Extract the weights using the correct key (try 'model_state' or 'state_dict')
# If you get a KeyError here, change 'model_state' to 'state_dict'
model.load_state_dict(checkpoint['model_state'])
# --- Step 4: TTA Validation ---
print("\nRunning Deterministic 8-way TTA on validation set...")
# FIXED: Using val_dataloader (clean images) and the new deterministic function
tta_preds, true_labels = run_deterministic_tta(model, val_dataloader, device, labeled=True)

tta_acc = (tta_preds == np.array(true_labels)).mean()
print(f"\nTTA Validation Accuracy: {100 * tta_acc:.2f}%")
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, tta_preds))
print("\nClassification Report:")
print(classification_report(true_labels, tta_preds, target_names=list(Class_Mapping.keys())))

# --- Step 5: TTA Test Submission ---
print("\nRunning Deterministic 8-way TTA on test set...")
# FIXED: Using test_dataloader (clean images)
tta_test_preds, filenames = run_deterministic_tta(model, test_dataloader, device, labeled=False)

submission_df = pd.DataFrame({'image_id': filenames, 'label': tta_test_preds})
submission_df = submission_df.sort_values('image_id').reset_index(drop=True)
submission_df.to_csv('2025MT11352_CNN.csv', index=False)
print(f"Submission saved — {len(submission_df)} predictions.")

Loading best checkpoint...

Running Deterministic 8-way TTA on validation set...

TTA Validation Accuracy: 99.04%

Confusion Matrix:
[[513   0   0   0   0   4   2   0   1   0]
 [  0 519   0   0   0   1   0   0   0   0]
 [  0   1 516   0   0   2   1   0   0   0]
 [  0   0   0 418   0   0   0   0   2   0]
 [  0   0   0   0 415   0   0   5   0   0]
 [  1   0   3   0   0 316   0   0   0   0]
 [  3   0  10   0   1   1 405   0   0   0]
 [  0   0   0   0   1   0   0 519   0   0]
 [  1   0   0   3   0   0   0   0 415   1]
 [  0   0   0   0   0   0   0   0   0 520]]

Classification Report:
                      precision    recall  f1-score   support

          AnnualCrop       0.99      0.99      0.99       520
              Forest       1.00      1.00      1.00       520
HerbaceousVegetation       0.98      0.99      0.98       520
             Highway       0.99      1.00      0.99       420
          Industrial       1.00      0.99      0.99       420
             Pasture       0.98      0.99      0.98       320
       PermanentCrop       0.99      0.96      0.98       420
         Residential       0.99      1.00      0.99       520
               River       0.99      0.99      0.99       420
             SeaLake       1.00      1.00      1.00       520

            accuracy                           0.99      4600
           macro avg       0.99      0.99      0.99      4600
        weighted avg       0.99      0.99      0.99      4600


Running Deterministic 8-way TTA on test set...
Submission saved — 4000 predictions.

**CONCLUSION**

The fine tuned model got more accuracy than the frozen backbone one, while the frozen backbone had validation accuracy of 97.85%, the fine tuned had an accuracy of 99.04%, while the ""heavier"" resnet 34 model trained from scratch had 98.7% accuracy, traiing from scratch required significantly more compute but still couldnt reach the high of 99.04% reached by the fine tuned model.

Training from scratch (Week 2) required 1 hour and 52 minutes to slowly build an understanding of visual features, taking 35 epochs just to cross the 95% threshold. Conversely, utilizing a frozen pre-trained backbone (Build 1) drastically reduced training time to just 43 minutes while converging instantly—hitting 95% accuracy in the very first epoch. The fine-tuned model (Build 2) offered the best compromise: requiring slightly more compute (~50 minutes) than the frozen model, but still cutting the training time by more than half compared to training from scratch, while rapidly converging past 97% by Epoch 3.

| Model Strategy | Architecture | Total Training Time | Epoch 1 Val Acc | Epochs to hit >95% | Final / TTA Accuracy |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **From Scratch** (Week 2) | ResNet-34 | **~112 mins** (1h 52m) | ~59.9% | Epoch 35 | ~98.6% |
| **Frozen Backbone** (Build 1)| ResNet-18 | **~43 mins** | ~95.0% | Epoch 1 | ~97.85% |
| **Fine-Tuned** (Build 2) | ResNet-18 | **~50 mins** | ~90.7% | Epoch 2 | **~99.04%** |